### ISSUE TITLE
"Code": 119,     "Message": "At least one Payment is required"

### ISSUE THREAD

**Issue by nicollaas94** [DeveloperCielo/API-3.0-PHP#10]
Olá, estou com problemas ao executar o exemplo do repositório.

Todas as dependências foram corretamente instanciadas, porem, o rest retorna o seguinte erro

Retorno
"Code": 119,     "Message": "At least one Payment is required"

Linha do exemplo onde o erro foi gerado
`    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);`

Como proceder?

Observe que o código foi 100% copiado do exemplo, sem qualquer alteração.

**Comment by nicollaas94** [comment]
Não vi sentido na função creditCard da classe Payment alterar o tipo para debitCard, isso está causando o erro 119
no modelo atual, isso torna obrigatório setar o Type como `Payment::PAYMENTTYPE_CREDITCARD` antes de adicionar um cartão de créditos.

`        // Crie uma instância de Credit Card utilizando os dados de teste
        // esses dados estão disponíveis no manual de integração
        $payment->setType(\Cielo\API30\Ecommerce\Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");`

**Comment by netojoaobatista** [comment]
Existe a possibilidade de transações por débito; por isso a necessidade de se especificar o tipo de pagamento. Essa especificação sempre foi obrigatória; quando se definia, porém, como cartão de crédito automaticamente, limitava a integração. Por isso foi removido do setter e deixado para que o desenvolvedor possa definir o tipo de pagamento que será utilizado no pedido.

Vou ajustar o exemplo no README.md para evitar confusões.
