### ISSUE TITLE
Os campo "identity type" e "delivery address" não são salvos via sdk para PHP

### ISSUE THREAD

**Issue by albertguedes** [DeveloperCielo/API-3.0-PHP#102]
Olá. Estou com um problema onde eu ao criar um pagamento, eu uso os campos  "identity type" e "delivery address" para o customer.

Até ai tudo bem, pois o pagamento é criado normalmente. O problema ocorre é na hora de consultar esses campos, pois eles são retornados como vazios, o que me faz crer que por algum motivo eles não estão sendo salvos, mas não sei dizer que é por algum problema no sdk ou no servidor da cielo.

Eu utilizo a sdk para PHP , já atualizei e não resolveu nada.

Desde já , agradeço a qualquer retorno.

**Comment by netojoaobatista** [comment]
Esses dados são informados na criação da transação e sua aplicação deve salvar numa base de dados. Mais detalhes sobre a [consulta de vendas](https://developercielo.github.io/manual/cielo-ecommerce#consultando-vendas), seus campos e significados, você encontra no manual.

**Comment by albertguedes** [comment]
Sim, eu sei que se faz na criação da transação, e os valores que envio via SDK são pegos exatamente de um banco de dados de minha loja eletronica.

Mas no SDK-PHP, nas classes de Customer e Address existem métodos para criação e consulta desses campos, não entendi porque eles existem se na api não vai retornar eles na consulta.

**Comment by netojoaobatista** [comment]
São setters e getters; você pode pegar aquilo você definir.

```php
$customer->setName('Fulano');

echo $customer->getName(); //Fulano
```
