### ISSUE TITLE
Problema com tokenizecard

### ISSUE THREAD

**Issue by Minotti** [DeveloperCielo/API-3.0-PHP#103]
Boa noite, estou com este problema e não consigo tokenizar um cartão.
![selecao_007](https://user-images.githubusercontent.com/17681478/35200163-df86e2b4-fee7-11e7-80f9-476934985135.png)

Os dados de testes enviados são estes:
"nome": "Marlon Teste Cartao",
"numero": "4539493804993474",
"cvv": "729",
"validade": "12/2020",
"bandeira": "Visa"

Também utilizei o número "4024007153763191" conforme o manual de integração

Utilizo a versão `1.2.1`

Também fiz o teste utilizando um client REST e obtive o resultado:
![selecao_008](https://user-images.githubusercontent.com/17681478/35200270-bafd674a-fee9-11e7-94e6-71579f596a05.png)

**Comment by frekele** [comment]
@Minotti 
Tudo bom,

eu também estava com problemas com 500 Internal Server, desde sabado até hoje as 16h + ou - .
https://github.com/DeveloperCielo/developercielo.github.io/issues/41

Após as 16h a API sandbox voltou a operar novamente.

**Comment by Minotti** [comment]
@frekele Perfeito, acabei de testar aqui e voltou ao normal.
