### ISSUE TITLE
Checkout vs API

### ISSUE THREAD

**Issue by DelBianco** [DeveloperCielo/API-3.0-PHP#109]
Eu posso usar a API e esse repositório mesmo que minha loja possua o contrato do Checkout cielo?
Com a idéia de que no futuro possa mudar o contrato com a cielo pra API?

Alguém sabe me informar se existe diferenças?

**Comment by v5manoel** [comment]
Existe diferença entre API e-Commerce Cielo e Checkout Cielo, ou seja, não tem como utilizar esse SDK para Checkout Cielo.

**Comment by DelBianco** [comment]
Obrigado @v5manoel
