### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by deyvisonbrandao** [DeveloperCielo/API-3.0-PHP#11]
Bom dia,

Tive grande dificuldade pra instalar o certificado ssl no meu projeto em Laravel. Após várias pesquisas ao tentar criar um pagamento, o mesmo me retorna a mensagem: "Curl error: SSL certificate problem: unable to get local issuer certificate". Após mais uma pesquisa, descomentei e alterei a seguinte linha no meu php.ini: curl.cainfo = "C:/wamp64/bin/php/php5.6.25/cacert.pem", mas após essa alteração me é retornado o seguinte erro: "Request Error" no CieloRequestException (400). Alguem podeira me ajudar com a instalação correta do certificado ou a resolução do erro 400?

**Comment by teuzinPereira** [comment]
Ola @deyvisonbrandao , estou com algumas dificuldades também nesta integração. Não sei exatamente como arrumar este erro, porem algumas coisas eu já sei. 
Primeiro: até no ambiente de sandbox, é necessário o SSL para funcionar corretamente. Este erro que você esta passando eu já solucionei porque tenho um servidor com SSL instalado. 
Segundo: Tem como sim usar localmente simulando o SSL (mas eu nao fiz isso :D), amigo meu seguiu este tutorial do stack:
http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate
E parece que nesse tutorial precisa de um certificado que esta disponível neste link:
[Certificado](https://l.facebook.com/l.php?u=https%3A%2F%2Fdevelopercielo.github.io%2FWebservice-3.0%2Fattachment%2FRaiz.crt&h=ATM1crTp1-ZYP42ENuuW77fmumKIm3EE33k_D8zaKWD11nho6F8Aa6o4Ao0Qy9GDUjMptvk4BuFBG_J_yUQxayN9rmHzfzgDL0usS4QZ0K7REircSFAtX6iNUZgQxyCTbgsxo_t4&s=1)

Tenta isso ai pra ver se da certo...

Abrass

**Comment by nicollaas94** [comment]
Acredito que seu erro seja o mesmo que o meu 

`119	At least one Payment is required	Nó “Payment” não enviado`

esse erro está ocorrendo pois o curl está sendo enviado de forma erronea no exemplo citado neste repositório.

modifique a linha 

`        // Crie uma instância de Credit Card utilizando os dados de teste
        // esses dados estão disponíveis no manual de integração
        $payment->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");`

Para 

`        // Crie uma instância de Credit Card utilizando os dados de teste
        // esses dados estão disponíveis no manual de integração
        $payment->setType(\Cielo\API30\Ecommerce\Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");`

**Comment by netojoaobatista** [comment]
Seu erro está relacionado com o tipo de pagamento, que deve ser obrigatoriamente enviado, @nicollaas94; com a última atualização feita, os setters já fazem essa definição para crédito e débito, então apenas atualize o SDK aí que isso foi resolvido. 

@deyvisonbrandao e @teuzinPereira, a integração precisa, necessariamente, ser feita via TLS 1.2. Apenas para simplificar o diagnóstico, isolem a integração do framework que estão utilizando e vejam se o erro persiste.

**Comment by deyvisonbrandao** [comment]
Bom ia @netojoaobatista , meu framework esta utilizando protocolo tls 1.2 conforme informações abaixo  do meu curl_version.

version_number:471553
age:3
features:266141
ssl_version_number:0
version:"7.50.1"
host:"x86_64-pc-win32"
ssl_version:"OpenSSL/1.0.2j"
libz_version:"1.2.7.3"
protocols:array(19)

**Comment by netojoaobatista** [comment]
O `CieloRequestException` tem uma propriedade para obter o `CieloError`. Qual o código e a mensagem de erro retornado?

```php
try {
    // ...
} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}
```

**Comment by deyvisonbrandao** [comment]
code: 999;
Message: "Value cannot be null.Parameter name: target"

**Comment by netojoaobatista** [comment]
Como está a parte do código de integração?

**Comment by deyvisonbrandao** [comment]
$environment = $environment = Environment::sandbox();

                    // Configure seu merchant
                    $merchant = new Merchant('c2ffc7c8-317f-460f-ade1-ba73942fbd8c', 'HFCINOKEWCSBKOTUITVNEWNDCPVTHFASQTPEEEEK');

                    // Crie uma instância de Sale informando o ID do pagamento
                    //$sale = new Sale($pedido->id);
                    $sale = new Sale('123');

                    // Crie uma instância de Customer informando o nome do cliente
                    //$customer = $sale->customer($formando->nome . ' ' . $formando->sobrenome);
                    $customer = $sale->customer('Fulano de Tal');

                    // Crie uma instância de Payment informando o valor do pagamento
                    //$payment = $sale->payment(str_replace(".","",str_replace(",","",$totalPedido)));
                    $payment = $sale->payment(15700);

                    // Crie uma instância de Credit Card utilizando os dados de teste
                    // esses dados estão disponíveis no manual de integração
                    $payment->creditCard("123", "Visa")
                            ->setExpirationDate("12/2018")
                            ->setCardNumber("0000000000000001")
                            ->setHolder("Fulano de Tal");

                    // Dados de Produção              
                    // $payment->creditCard($codSeguranca, $bandeiraCartao)
                    //         ->setExpirationDate($dataValidade)
                    //         ->setCardNumber(str_repeat(" ","",$numeroCartao))
                    //         ->setHolder($nomeCartao);

                    // Crie o pagamento na Cielo
                    try {
                        // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
                        $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

                        // Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
                        // dados retornados pela Cielo
                        $paymentId = $sale->getPayment()->getPaymentId();

                        // Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
                        //$sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);

                        // E também podemos fazer seu cancelamento, se for o caso
                        //$sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);
                    } catch (CieloRequestException $e) {
                        // Em caso de erros de integração, podemos tratar o erro aqui.
                        // os códigos de erro estão todos disponíveis no manual de integração.
                        $error = $e->getCieloError();
                    }

**Comment by netojoaobatista** [comment]
@deyvisonbrandao,

Logo na primeira linha do seu código, onde está 

```php
$environment = $environment = Environment::sandbox();
```

troque para:

```php
$environment = Environment::sandbox();
```

Salve e faça um `composer update`. Depois de atualizada a dependência, execute novamente e veja se o problema persiste.

**Comment by netojoaobatista** [comment]
Acabei de executar seu código aqui de forma isolada e ele está funcionando perfeitamente.

**Comment by deyvisonbrandao** [comment]
Mesmo fazendo as alterações na integração o erro persiste.

**Comment by deyvisonbrandao** [comment]
Apos atualização da sdk integração funcionando normalmente.
