### ISSUE TITLE
Dúvidas referente a integração.

### ISSUE THREAD

**Issue by emalherbi** [DeveloperCielo/API-3.0-PHP#111]
Boa Tarde.

Estou fazendo a integração conforme exemplos e me surgiu algumas dúvidas. Tanto o pagamento débito/crédito estão funcionando, gerando o paymentId, conforme exemplo abaixo.

```php
try {
  $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);
  $idPayment = $sale->getPayment()->getPaymentId();
} catch (CieloRequestException $e) {
  $error = $e->getCieloError();      
}
```
Porem quando eu utilizo o método ```getReturnCode()``` o mesmo retorna "4" e mensagem "Operation Successful", conforme exemplo.

```php
$sale->getPayment()->getReturnCode();
```

Entretanto no manual não estou achando os códigos de retorno que estão de acordo com o retorno do php.

[Manual](https://developercielo.github.io/manual/cielo-ecommerce#c%C3%B3digos-de-retorno-das-vendas)

Desde já agradeço.

Obrigado.

**Comment by emalherbi** [comment]
@muvasco Muito Obrigado. Para realizar os testes da api a melhor forma é fazer em produção que já deve estar correto? Isso.

**Comment by emalherbi** [comment]
@muvasco outra questão. Quando eu chamar o método: 

```
$sale->getPayment()->getStatus(); (não sei se esse método pois não testei)
```

O retorno será uma string ou um nro? Eu devo tratar por codigo "1" ou "PaymentConfirmed"?

**Comment by netojoaobatista** [comment]
@emalherbi, você tem o código de status e o código de retorno de vendas.

> O retorno será uma string ou um nro?

Será uma string, mas o PHP lida com o cast para você.

> Eu devo tratar por codigo "2" ou "PaymentConfirmed"?

Você deve tratar exatamente como descrito no manual: https://developercielo.github.io/manual/cielo-ecommerce#c%C3%B3digos-da-api

**Comment by emalherbi** [comment]
Tudo certo. 

@netojoaobatista obrigado.
@muvasco obrigado.
