### ISSUE TITLE
URL de notificação

### ISSUE THREAD

**Issue by maykondeveloper** [DeveloperCielo/API-3.0-PHP#116]
Seria muito melhor se a cielo permitisse que o desenvolvedor enviasse a url que receberá as notificações da cielo, atualmente temos que enviar um e-mail para o suporte informando a url que queremos.

**Comment by v5manoel** [comment]
Verdade, outras adquirentes permitem o envio da url de notificação na requisição, o que facilita muito a configuração da integração completa.
