### ISSUE TITLE
RecurrentPaymentId

### ISSUE THREAD

**Issue by arturcesarmelo** [DeveloperCielo/API-3.0-PHP#13]
Olá,

Na transação recorrente, o json de retorno trás um objeto RecurrentPayment com um atributo "recurrentPaymentId". Na classe (php) RecurrentPayment não existe esse atributo. seria o caso adicionar esse atributo?

Na documentação e na internet o TID e o Payment_id são unicos para cada parcela (procede?) ao passo que o RecurrentPaymentId é o identificador em comum para aquele grupo de parcela (correto?).

**Comment by netojoaobatista** [comment]
> Na classe (php) RecurrentPayment não existe esse atributo. seria o caso adicionar esse atributo?

Correto.

> Na documentação e na internet o TID e o Payment_id são unicos para cada parcela (procede?) ao passo que o RecurrentPaymentId é o identificador em comum para aquele grupo de parcela (correto?).

Correto; na recorrência funciona assim:

* `TID` - identificador de cada transação, ou seja, numa recorrência mensal de 1 ano, teremos 12 transações e 12 TID.
* `RecurrentPaymentId` - é o identificador único da própria recorrência e identifica todas as transações daquela recorrência.

**Comment by arturcesarmelo** [comment]
Obrigado pela resposta. Iremos fazer o pull request em breve.

**Comment by netojoaobatista** [comment]
Legal, @arturcesarmelo!
