### ISSUE TITLE
API esta preparada para a Autenticação 3DS 2.0?

### ISSUE THREAD

**Issue by souzadavi** [DeveloperCielo/API-3.0-PHP#141]
Olá boa tarde, essa API esta preparada para a Autenticação 3DS 2.0?

https://developercielo.github.io/manual/emv3ds#autentica%C3%A7%C3%A3o-3ds-2.0

Obrigado.

**Comment by souzadavi** [comment]
Não, a autenticação 3DS ainda não esta funcionando corretamente em todas as bandeiras de cartão de crédito.

**Comment by MestreMagento** [comment]
@souzadavi sabe se esse SDK PHP esta preparada para autenticação 3DS 2.0? Você conseguiu implementar?

**Comment by souzadavi** [comment]
Não sei se o SDK esta preparado para 3DS. Eu consegui implementar o 3DS mas acabei desenvolvendo algo próprio.O 3DS é algo muito recente. O 3DS esta funcionando em uma pequena parte dos cartões.
