### ISSUE TITLE
Variavel

### ISSUE THREAD

**Issue by paulortoledo** [DeveloperCielo/API-3.0-PHP#152]
Olá. Sou iniciante na integração. Gostaria de saber como fazer para pegar o numero do cartão retornado pela cielo.

[cardNumber:Cielo\API30\Ecommerce\CreditCard:private] => 000000******0001

$VARIAVEL = ??

**Comment by edson-nascimento** [comment]
> Olá. Sou iniciante na integração. Gostaria de saber como fazer para pegar o numero do cartão retornado pela cielo.
> 
> [cardNumber:Cielo\API30\Ecommerce\CreditCard:private] => 000000******0001
> 
> $VARIAVEL = ??

Depois que criar a venda como nos exemplos da documentação você pode chamar:
crédito
`$sale->getPayment()->getCreditCard()->getCardNumber()`

ou débito
`$sale->getPayment()->getDebitCard()->getCardNumber()`

**Comment by paulortoledo** [comment]
Muito obrigado. Perfeito.
