### ISSUE TITLE
Retorno após pagamento boleto

### ISSUE THREAD

**Issue by DaniloAguiar** [DeveloperCielo/API-3.0-PHP#158]
Ola,

Como posso saber se um boleto foi pago? apos o boleto ser pago tem algum tipo de rentorno, como no pagamento de cartao de debito?

**Comment by alyleite** [comment]
@DaniloAguiar descobriu como?

**Comment by DaniloAguiar** [comment]
Os Boleto da cielo e gerado pelos bancos conveniado (acho que e o Santander), então o responsavel pelo retorno e o banco. A cielo só da uma interface para gerar o boleto, mas o retorno e o banco que oferece.

**Comment by alyleite** [comment]
Entendi, vlew
