### ISSUE TITLE
Retorno "0 - Internal Error" no captureSale do SandBox

### ISSUE THREAD

**Issue by marinoboscolo** [DeveloperCielo/API-3.0-PHP#164]
Está retornando um erro "0 - Internal Error" no captureSale do SandBox.

Vi na estrutura da classe que só o paymentID é required para realizar essa consulta, mas não consigo ter certeza se minha implementação funcionará em produção.

Atualizei a classe "no braço" com a versão 1.3.1, mas a versão do composer também retorna o mesmo erro.

É um erro de vocês aí?

**Comment by marinoboscolo** [comment]
OBS: pelo postman, funciona normal.
Segue código (muito simples) que dispara o erro em PHP:

`class CieloExemplo {
    protected $venda;
	protected $environment;
	protected $merchant;
	protected $ecommerce;

	function __construct(){
		$this->environment = Environment::sandbox();
		$this->merchant = new Merchant(CIELO_MID, CIELO_MKEY);
	}

	function captureSale($paymentId){
		try {
			$this->ecommerce = $this->ecommerce ?: new CieloEcommerce($this->merchant, $this->environment);
			$sale = $this->ecommerce->captureSale($paymentId);
			return $sale;
		} catch (CieloRequestException $e) {
			$error = $e->getCieloError();
		}
	}
}

$cielo = new CieloExemplo();
$cielo->captureSale("ab56d0da-2245-45fa-bee0-6ef7814e7a21");`

**Comment by edson-nascimento** [comment]
> OBS: pelo postman, funciona normal.
> Segue código (muito simples) que dispara o erro em PHP:
> 
> `class CieloExemplo {
> protected $venda;
> protected $environment;
> protected $merchant;
> protected $ecommerce;
> 
> ```
> function __construct(){
> 	$this->environment = Environment::sandbox();
> 	$this->merchant = new Merchant(CIELO_MID, CIELO_MKEY);
> }
> 
> function captureSale($paymentId){
> 	try {
> 		$this->ecommerce = $this->ecommerce ?: new CieloEcommerce($this->merchant, $this->environment);
> 		$sale = $this->ecommerce->captureSale($paymentId);
> 		return $sale;
> 	} catch (CieloRequestException $e) {
> 		$error = $e->getCieloError();
> 	}
> }
> ```
> 
> }
> 
> $cielo = new CieloExemplo();
> $cielo->captureSale("ab56d0da-2245-45fa-bee0-6ef7814e7a21");`

Eu tenho um ambiente de sandbox aqui e esta funcionando tudo certo.
Verifique algumas coisas:

* Antes de criar o pedido se o $capture do Payment está como false
* Verifique se o pedido que está querendo capturar está com o status 1 "Authorized"

Se nenhuma der certo tbm pode tentar criar uma nova conta no sandbox para ver se é um bug na conta.

**Comment by marinoboscolo** [comment]
> > OBS: pelo postman, funciona normal.
> > Segue código (muito simples) que dispara o erro em PHP:
> > `class CieloExemplo {
> > protected $venda;
> > protected $environment;
> > protected $merchant;
> > protected $ecommerce;
> > ```
> > function __construct(){
> > 	$this->environment = Environment::sandbox();
> > 	$this->merchant = new Merchant(CIELO_MID, CIELO_MKEY);
> > }
> > 
> > function captureSale($paymentId){
> > 	try {
> > 		$this->ecommerce = $this->ecommerce ?: new CieloEcommerce($this->merchant, $this->environment);
> > 		$sale = $this->ecommerce->captureSale($paymentId);
> > 		return $sale;
> > 	} catch (CieloRequestException $e) {
> > 		$error = $e->getCieloError();
> > 	}
> > }
> > ```
> > 
> > 
> > }
> > $cielo = new CieloExemplo();
> > $cielo->captureSale("ab56d0da-2245-45fa-bee0-6ef7814e7a21");`
> 
> Eu tenho um ambiente de sandbox aqui e esta funcionando tudo certo.
> Verifique algumas coisas:
> 
> * Antes de criar o pedido se o $capture do Payment está como false
> * Verifique se o pedido que está querendo capturar está com o status 1 "Authorized"
> 
> Se nenhuma der certo tbm pode tentar criar uma nova conta no sandbox para ver se é um bug na conta.

Obrigado @edson-nascimento. Criei outro ambiente sandbox e funcionou.
