### ISSUE TITLE
Problema ao Gerar Boleto

### ISSUE THREAD

**Issue by andrefelipeschulle** [DeveloperCielo/API-3.0-PHP#165]
Bom dia galera, estou com um problema ao gerar boleto pelo SDK PHP 3.0, pelo sandbox está funcionando 100%, más quando uso no modo production não está funcionando, " o cartão de crédito está funcionando 100% no modo production, já apareceu a cobrança no cartão e tudo mais ". 

Fatal error: Uncaught Cielo\API30\Ecommerce\Request\CieloRequestException: Unknown status in /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php:148 Stack trace: #0 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php(114): Cielo\API30\Ecommerce\Request\AbstractRequest->readResponse(401, '') #1 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/CreateSaleRequest.php(45): Cielo\API30\Ecommerce\Request\AbstractRequest->sendRequest('POST', 'https://api.cie...', Object(Cielo\API30\Ecommerce\Sale)) #2 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(66): Cielo\API30\Ecommerce\Request\CreateSaleRequest->execute(Object(Cielo\API30\Ecommerce\Sale)) #3 /var/www/indipeso.com.br/function/cielo/efetuar-pagamento.php(179): Cielo\API30\Ecommerce\CieloEcommerce->createSale(Object(Cielo\API30\Ecommerce\Sale)) #4 {main} th in /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php on line 148

este é o erro.

**Comment by edson-nascimento** [comment]
> Bom dia galera, estou com um problema ao gerar boleto pelo SDK PHP 3.0, pelo sandbox está funcionando 100%, más quando uso no modo production não está funcionando, " o cartão de crédito está funcionando 100% no modo production, já apareceu a cobrança no cartão e tudo mais ".
> 
> Fatal error: Uncaught Cielo\API30\Ecommerce\Request\CieloRequestException: Unknown status in /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php:148 Stack trace: #0 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php(114): Cielo\API30\Ecommerce\Request\AbstractRequest->readResponse(401, '') #1 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/CreateSaleRequest.php(45): Cielo\API30\Ecommerce\Request\AbstractRequest->sendRequest('POST', 'https://api.cie...', Object(Cielo\API30\Ecommerce\Sale)) #2 /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(66): Cielo\API30\Ecommerce\Request\CreateSaleRequest->execute(Object(Cielo\API30\Ecommerce\Sale)) #3 /var/www/indipeso.com.br/function/cielo/efetuar-pagamento.php(179): Cielo\API30\Ecommerce\CieloEcommerce->createSale(Object(Cielo\API30\Ecommerce\Sale)) #4 {main} th in /var/www/indipeso.com.br/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php on line 148
> 
> este é o erro.

Olá @andrefelipeschulle você já conferiu se o serviço de emissão de boletos está habilitado e configurado na sua conta da cielo, porque se não me engano ele não vem ativado por padrão, já  tive que fazer algumas solicitação para eles ativarem o serviço.

**Comment by andrefelipeschulle** [comment]
já sim, entrei em contato, eles falaram que está habilitado... não sei realmente o que fazer

**Comment by edson-nascimento** [comment]
> já sim, entrei em contato, eles falaram que está habilitado... não sei realmente o que fazer

Vai ter que dar uma debugada, da uma olhada se está chegando algo no $responseBody já que $statusCode não veio.
```php
//AbstractRequest.php
protected function readResponse($statusCode, $responseBody)
```
Se quiser postar o código do request tbm ajuda.

**Comment by andrefelipeschulle** [comment]
// Informações do Cliente no Boleto
    $customer = $sale->customer($cliente->razao)
        ->setIdentity($cliente->cnpj)
        ->setIdentityType($tipo_cadastro)
        ->address()->setZipCode($cliente->cep)
            ->setCountry('BRA')
            ->setState('SC')
            ->setCity($cliente->cidade)
            ->setDistrict($cliente->bairro)
            ->setStreet($cliente->endereco)
            ->setNumber($cliente->numero);


    // Crie uma instância de Payment informando o valor do pagamento
    $payment = $sale->payment((int) ($ValorTotal), 1);

    //$payment->setCapture(1);

    $payment->setType(Payment::PAYMENTTYPE_BOLETO)
        ->setAmount((int) ($ValorTotal))
        ->setProvider('BancodoBrasil2')
        ->setAddress('Rua Selesta Fronza, n430, Rio do Sul - SC')
        ->setBoletoNumber('1235')
        ->setAssignor('INDIPESO INSTR. ELETRONICOS')
        ->setDemonstrative('Boleto do Pedido #' . $IdPedido)
        ->setExpirationDate(date('d/m/Y', strtotime('+1 month')))
        ->setIdentification('11884926754')
        ->setInstructions('Senhor Caixa, Não Aceitar Pagamento deste Boleto Após o Vencimento');


    // Crie o pagamento na Cielo
    try {

        $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

        $paymentId = $sale->getPayment()->getPaymentId();

        echo $sale->getPayment()->getStatus();
        echo "-";
        echo $sale->getPayment()->getReturnCode();
        echo "<pre>";
        print_r($sale->getPayment());
        die();

        $pagamento_order = new Payment_Order('', $pedido->id, '0', $paymentId, '3', date('Y-m-d'), date('H:i:s'));
        $pagamento_order->CriarPagamento();


        Header("Location: " . $sale->getPayment()->getUrl());
    } catch (CieloRequestException $e) {

        Header("Location: ./../../../pages/retorno-cielo.php?cod=2&erro=" . $e->getCieloError()->getCode());
    }

**Comment by andrefelipeschulle** [comment]
`// Informações do Cliente no Boleto
    $customer = $sale->customer($cliente->razao)
        ->setIdentity($cliente->cnpj)
        ->setIdentityType($tipo_cadastro)
        ->address()->setZipCode($cliente->cep)
            ->setCountry('BRA')
            ->setState('SC')
            ->setCity($cliente->cidade)
            ->setDistrict($cliente->bairro)
            ->setStreet($cliente->endereco)
            ->setNumber($cliente->numero);


    // Crie uma instância de Payment informando o valor do pagamento
    $payment = $sale->payment((int) ($ValorTotal), 1);

    //$payment->setCapture(1);

    $payment->setType(Payment::PAYMENTTYPE_BOLETO)
        ->setAmount((int) ($ValorTotal))
        ->setProvider('BancodoBrasil2')
        ->setAddress('Rua Selesta Fronza, n430, Rio do Sul - SC')
        ->setBoletoNumber('1235')
        ->setAssignor('INDIPESO INSTR. ELETRONICOS')
        ->setDemonstrative('Boleto do Pedido #' . $IdPedido)
        ->setExpirationDate(date('d/m/Y', strtotime('+1 month')))
        ->setIdentification('11884926754')
        ->setInstructions('Senhor Caixa, Não Aceitar Pagamento deste Boleto Após o Vencimento');


    // Crie o pagamento na Cielo
    try {

        $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

        $paymentId = $sale->getPayment()->getPaymentId();

        echo $sale->getPayment()->getStatus();
        echo "-";
        echo $sale->getPayment()->getReturnCode();
        echo "<pre>";
        print_r($sale->getPayment());
        die();

        $pagamento_order = new Payment_Order('', $pedido->id, '0', $paymentId, '3', date('Y-m-d'), date('H:i:s'));
        $pagamento_order->CriarPagamento();


        Header("Location: " . $sale->getPayment()->getUrl());
    } catch (CieloRequestException $e) {

        Header("Location: ./../../../pages/retorno-cielo.php?cod=2&erro=" . $e->getCieloError()->getCode());
    }`

**Comment by andrefelipeschulle** [comment]
var_dump do statusCode 
string(0) "" int(401)
var_dump do $responsyBody
string(0)

**Comment by edson-nascimento** [comment]
> 11884926754

A principio parece tudo certo, deve ser alguma regra na geração do boleto tipo (Comentário Banco Do Brasil: Os campos Customer.Address.Street; Customer.Address.Number; Customer.Address.Complement; Customer.Address.District devem totalizar até 60 caracteres.)
Da uma conferida nas regras e tamanho dos campos https://developercielo.github.io/manual/cielo-ecommerce#boleto e manda somente os campos obrigatórios, também não custa tirar as palavras com acentuação para eliminar a chance de ser algum erro de encode.
Se nada funcionar tenta alterar um pouco informações ex: data de expiração, instruções...

**Comment by NathanMacedo** [comment]
Tive o mesmo problema de retorno porém estava usando a constante da cielo do provider. ao utilizar o set provider do payment com o nome dessa forma passou a funcionar.

->setProvider('BancoDoBrasil2') 

Veja se escrevendo exatamente dessa forma funcionaria pra ti

Att.

**Comment by ahmadabdouni** [comment]
Andre, Boa Tarde!

Tenta realizar teste com este codigo:

<?php

$request = new HttpRequest();
$request->setUrl('https://api.cieloecommerce.cielo.com.br/1/sales/');
$request->setMethod(HTTP_METH_POST);

$request->setHeaders(array(
  'Postman-Token' => 'a64050d9-017d-4c4e-9b50-93ef341e35a8',
  'cache-control' => 'no-cache',
  'Content-Type' => 'application/json',
  'MerchantKey' => 'DIGITE SEU KEY AQUI',
  'MerchantId' => 'DIGITE SEU MID AQUI'
));

$request->setBody('{  
    "MerchantOrderId":"2014111706",
    "Customer":
    {  
        "Name":"Comprador Teste Boleto",
        "Identity": "1234567890",
        "Address":
        {
          "Street": "Avenida Marechal Câmara",
          "Number": "160",    
          "Complement": "Sala 934",
          "ZipCode" : "22750012",
          "District": "Centro",
          "City": "Rio de Janeiro",
          "State" : "RJ",
          "Country": "BRA"
        }
    },
    "Payment":
    {  
        "Type":"Boleto",
        "Amount":15700,
        "Provider":"INCLUIR PROVIDER",
        "Address": "Rua Teste",
        "BoletoNumber": "123",
        "Assignor": "Empresa Teste",
        "Demonstrative": "Desmonstrative Teste",
        "ExpirationDate": "2020-12-31",
        "Identification": "11884926754",
        "Instructions": "Aceitar somente até a data de vencimento, após essa data juros de 1% dia."
    }
}');

try {
  $response = $request->send();

  echo $response->getBody();
} catch (HttpException $ex) {
  echo $ex;
}

Realizei uma transferência de JSON para PHP o código
Obs: não esqueça de informar o MID, KEY e Provider.

Att
Ahmad Abdouni

**Comment by andrefelipeschulle** [comment]
olá pessoal, consegui resolver o problema, parece que estava com problemas na merchant Key, a Cielo fez chaves novas e resolveu o problema. 
Obrigado a Todos Pela Ajuad

**Comment by andrefelipeschulle** [comment]
olá pessoal, consegui resolver o problema, parece que estava com problemas na merchant Key, a Cielo fez chaves novas e resolveu o problema. 
Obrigado a Todos Pela Ajuda
