### ISSUE TITLE
Tradução dos erros.

### ISSUE THREAD

**Issue by JoaoWitorFelipe** [DeveloperCielo/API-3.0-PHP#166]
Olá galera, gostaria de saber se é possível traduzir as mensagens de erros ou pegar a descrição (já que no manual mostra a descrição em português) que é retornado após fazer um pagamento com o cartão de crédito.
Li no manual de integração que por padrão é retornado em português, mas quando o ocorre um erro é retornado o seguinte erro: "Credit Card Expiration Date is invalid".

**Comment by ahmadabdouni** [comment]
Joao, Boa Tarde!

Teria a requisição para que possa ser feito a analise do erro?
Fico no aguardo!

Att
Ahmad Abdouni

**Comment by JoaoWitorFelipe** [comment]
`{
	 "MerchantOrderId":"2014111703",
   "Customer":{
      "Name":"Comprador crédito simples"
   },
   "Payment":{
     "Type":"CreditCard",
     "Amount":15700,
     "CreditCard":{
         "CardNumber":"1234123412341231",
         "Holder":"Teste Holder",
         "ExpirationDate":"00/0000",
         "SecurityCode":"5464654564",
         "Brand":"Visa"
     }
   }
}`

**Comment by ahmadabdouni** [comment]
Joao, 

O erro gerado ocorre no objeto "SecurityCode" pois esta sendo informado um valor acima do permitido, vou pedir pro senhor realizar novos testes com securitycode "123", obs: lembrando que no manual os códigos de retorno da api são todos em inglês infelizmente!

Att
Ahmad Abdouni
cieloecommerce@cielo.com.br
Telefones: 4002-9700 (Capitais e regiões metropolitanas)
0800 570 8472 (Demais regiões)

**Comment by JoaoWitorFelipe** [comment]
Okay então, obrigado pelo retorno
