### ISSUE TITLE
Consulta Venda Recorrente

### ISSUE THREAD

**Issue by arturcesarmelo** [DeveloperCielo/API-3.0-PHP#19]
@netojoaobatista Como podemos fazer, por meio dessa integração, uma consulta das vendas (recorrentes) para podermos dar baixa nas parcelas pagas no nosso sistema?

**Comment by netojoaobatista** [comment]
@arturcesarmelo:

```php
$recurrentPayment = (new CieloEcommerce($merchant, $environment))->getRecurrentPayment($recurrentPaymentId);
```

**Comment by arturcesarmelo** [comment]
Obrigado
