### ISSUE TITLE
Transação com Parcelas Credito

### ISSUE THREAD

**Issue by BrunoPignatari** [DeveloperCielo/API-3.0-PHP#198]
no objeto instanciado, os valores da parcela são feitos automaticamente ?

$sale->payment("20000",'2'); 

logo terei parcelas de 
100,00
100,00 
?

**Comment by edson-nascimento** [comment]
Isso é um padrão da maioria das apis de pagamento, você só envia o valor total e número de parcelas a parte do calculo do valor da parcela é feito pela adquirente, no caso a cielo.

**Comment by BrunoPignatari** [comment]
imaginei, excelente ! Muito obrigado !
