### ISSUE TITLE
Exemplo de Silent Order Post 

### ISSUE THREAD

**Issue by lucasbelini** [DeveloperCielo/API-3.0-PHP#201]
Alguém teria um exemplo de como usar o silent order post? achei a documentação um pouco confusa, eu entendi que é preciso fazer a requisição do access token, passar ele para o javascript fornecido pela cielo e depois disso é retornado um payment token , mas como é utilizado este payment token? se alguém tiver um exemplo melhor do que aquele da documentação cielo eu ficaria agradecido se pudesse compartilhar.

**Comment by souzadavi** [comment]
@lucasbelini o da documentação funciona certinho. Eu testei aqui e rodou.. Veja o diagrama do fluxo com atenção para entender todas as etapas.

**Comment by lucasbelini** [comment]
Valeu, eu consegui fazer rodar sim, na verdade eu estava com um problema na Cielo, eles criaram multiplas chaves, achei que fosse o código mas não era hahaha, resolvi tudo ligando lá, muito obrigado.
