### ISSUE TITLE
API 3.0 trava ao retornar status da transação

### ISSUE THREAD

**Issue by playgb** [DeveloperCielo/API-3.0-PHP#208]
Estava tudo funcionando perfeitamente antes do dia 01/11/2020, a partir desse dia, minhas transações pela Cielo ficaram todas com status Pendente.

Isso ocorreu porque a linha: **$pegaStatus = $sale->getPayment()->getStatus();** deixou de retornar **2** ou **3** como de costume e passou a encerrar o script com o seguinte erro:

**PHP Catchable fatal error:  Argument 1 passed to Cielo\\API30\\Ecommerce\\Sale::populate() must be an instance of stdClass.**

Eu vi que outras pessoas estão com o mesmo problema aqui também.

Não sei se é coincidência, mas até agora o script só travou quando a transação deu aprovada. Transação rejeitada, o retorno vem 3 normalmente, só quando da aprovada que gera esse erro.

**Comment by victornovy** [comment]
Estamos passando pelo mesmo problema!

**Comment by IsabellaCerbino** [comment]
Mesmo problema aqui!

**Comment by MenezesLucas** [comment]
Também estou com o mesmo problema!

**Comment by samuelcunha** [comment]
Estou com o mesmo problema por aqui!

**Comment by paulociva** [comment]
Mesmo problema aqui!

**Comment by williamazevedodepaula** [comment]
Mesmo problema aqui!

**Comment by victorapa** [comment]
Também estou com o mesmo problema!

**Comment by rabraga** [comment]
muitas pessoas com o mesmo problema!

**Comment by luizmacfilho** [comment]
:+1:

**Comment by LucasHaddad** [comment]
o/

**Comment by elvispdosreis** [comment]
Tambem estou com o mesmo problema parece que esta retornando um binario

src\Cielo\API30\Ecommerce\Request\AbstractRequest.php
Linha 52 remova 'Accept-Encoding: gzip',

**Comment by playgb** [comment]
> Tambem estou com o mesmo problema parece que esta retornando um binario
> 
> src\Cielo\API30\Ecommerce\Request\AbstractRequest.php
> Linha 52 remova 'Accept-Encoding: gzip',
> 
> ou
> 
> [a79f805](https://github.com/DeveloperCielo/API-3.0-PHP/commit/a79f8050ca174f85a478f1a9aecb6cd5a09fd062)

Testei sua solução, mas não funcionou. Removi a linha 52, mas continua dando o mesmo problema.

**Comment by elvispdosreis** [comment]
faz isso deve resolver
[image: image.png]

Em qui., 12 de nov. de 2020 às 02:12, Play GB Games <
notifications@github.com> escreveu:

**Comment by cardonazio** [comment]
olá tentei realizar os ajustes acima porem sem sucesso.  alguém conseguiu alguma outro solução.

**Comment by elvispdosreis** [comment]
qual a versão do seu php?

Em qui., 12 de nov. de 2020 às 13:50, Rafael Cardonazio <
notifications@github.com> escreveu:

**Comment by cardonazio** [comment]
Boa tarde,

PHP Version 5.6.40-0+deb8u12

Att.

[cid:image001.png@01D6B90B.D597C300]<http://www.agenciadream.com/>

Rafael Agostinho Cardonazio
http://www.agenciadream.com
skype: rafael.agotinho.cardonazio
Celular: (43) 9983-4049
Tecnólogo em Sistemas de Informação
Especialista em Banco de Dados
MBA em Projetos

A informática está interligada ao mundo sobre as reações intergalaxias!
Bill Gates



De: Elvis P dos Reis <notifications@github.com>
Enviada em: quinta-feira, 12 de novembro de 2020 15:40
Para: DeveloperCielo/API-3.0-PHP <API-3.0-PHP@noreply.github.com>
Cc: Rafael Cardonazio <sarrafo_rafa@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [DeveloperCielo/API-3.0-PHP] API 3.0 trava ao retornar status da transação (#208)

qual a versão do seu php?

Em qui., 12 de nov. de 2020 às 13:50, Rafael Cardonazio <
notifications@github.com<mailto:notifications@github.com>> escreveu:

**Comment by abraaolevi** [comment]
@cardonazio ao invés de `??` você pode usar `?:` para manter a compatibilidade com a versão 5.6 do php, tem um exemplo no PR https://github.com/DeveloperCielo/API-3.0-PHP/pull/207 :+1:

**Comment by playgb** [comment]
Tava esperando dia 13 chegar pra testar. Deu tudo certo agora, muito obrigado elvispdosreis! Removi a linha 52 do arquivo AbstractRequest.php e voltou a funcionar!

**Comment by cardonazio** [comment]
> @cardonazio ao invés de `??` você pode usar `?:` para manter a compatibilidade com a versão 5.6 do php, tem um exemplo no PR #207 👍

obrigado deu certo !! valeus.
