### ISSUE TITLE
Implementação da Autenticação 3DS 2.0

### ISSUE THREAD

**Issue by yurigebit** [DeveloperCielo/API-3.0-PHP#209]
[(Relacionado](https://github.com/DeveloperCielo/API-3.0-PHP/issues/141))

Estou tentando implementar a Autenticação 3DS 3.0 usando [esta](https://developercielo.github.io/manual/3ds) e [esta](https://developercielo.github.io/manual/autorizacao-com-autenticacao) página como guia.

Para isto criei uma extenção das classes `Cielo\API30\Ecommerce\Sale` e `Cielo\API30\Ecommerce\Payment`, e em `Payment` criei um atributo `externalAuthentication`; criei uma classe para este atributo também.

O `json_encode($payment)` fica assim: <details><summary>mostrar</summary>
```
{
    "serviceTaxAmount": null,
    "installments": 1,
    "interest": null,
    "capture": false,
    "authenticate": false,
    "recurrent": null,
    "recurrentPayment": null,
    "creditCard": {
        "cardNumber": "4000000000000002",
        "holder": "Comprador de Teste",
        "expirationDate": "01\/2021",
        "securityCode": null,
        "saveCard": false,
        "brand": "4000000000000002",
        "cardToken": null,
        "customerName": null,
        "links": null
    },
    "debitCard": null,
    "authenticationUrl": null,
    "tid": null,
    "proofOfSale": null,
    "authorizationCode": null,
    "softDescriptor": "",
    "returnUrl": "http:\/\/teste.com",
    "provider": null,
    "paymentId": null,
    "type": "CreditCard",
    "amount": "1000",
    "receivedDate": null,
    "capturedAmount": null,
    "capturedDate": null,
    "voidedAmount": null,
    "voidedDate": null,
    "currency": null,
    "country": null,
    "returnCode": null,
    "returnMessage": null,
    "status": null,
    "links": null,
    "extraDataCollection": null,
    "expirationDate": null,
    "url": null,
    "number": null,
    "boletoNumber": null,
    "barCodeNumber": null,
    "digitableLine": null,
    "address": null,
    "assignor": null,
    "demonstrative": null,
    "identification": null,
    "instructions": null,
    "ExternalAuthentication": {
        "Cavv": "AAABAWFlmQAAAABjRWWZEEFgFz+=",
        "Xid": "WU5IYmRUZVZpZXpVdWU0UlhFNzA=",
        "Eci": "05",
        "Version": "1",
        "ReferenceId": null
    }
}
```

</details>

Entretanto estou recebendo um erro com o código `234` e a mensagem `External Authentication is not supported for the given brand.`.

Este erro parece dizer que a bandeira deste cartão não é suportada, porém isto não deveria ser possível porque estou passando um cartão Visa exatamente como está neste (código de exemplo)[https://github.com/DeveloperCielo/developercielo.github.io/blob/docs/_i18n/pt/_posts/3ds/exemplo.html] (código de exemplo para implementar o 3DS).

Alguém sabe o motivo do erro?
Este pacote terá um dia suporte ao 3DS?

**Comment by wagnerr63** [comment]
Boa tarde @yurigebit . Como você fez para o ExternalAuthentication popular estes dados? Cavv, Cavv, Eci e etc.;
No meu os campos vem todos nulos.

**Comment by yurigebit** [comment]
Acredito que meu problema está mais relacionado aos endpoints do 3DS 2.0 do que ao SDK, mas vlw pelo suporte

**Comment by jodaias** [comment]
Olá @yurigebit Faz muito tempo... mas aparentemente o erro é porque você colocou o número do cartão no local onde deveria colocar o nome da Bandeira:
Como está:

"creditCard": {
         ...
        "brand": "4000000000000002",
         ...
 },
Como deve ser:
"creditCard": {
         ...
        "brand": "Visa",
         ...
 },
