### ISSUE TITLE
Parcelamento

### ISSUE THREAD

**Issue by rodrigomgrassioto** [DeveloperCielo/API-3.0-PHP#212]
Boa tarde.

Sou novo em PHP, Estou fazendo um projeto que o cliente vai utilizar a Cielo. Usando já fiz a integração usando sandbox.
Até ai está tudo ok. Consigo receber a resposta da Cielo e tratar ela. 

Só não achei onde vai a informação de parcelamento. Onde vai essa informação?

encontrei essa opção:
// Configure o pagamento recorrente
$payment->recurrentPayment(true)->setInterval(RecurrentPayment::INTERVAL_MONTHLY);

mas acredito que aqui seria pra pagamento tipo assinatura, como na netflix. Correto?

O o projeto que estou fazendo não é assinatura, é venda de produtos,  Posso dividir o valor total da compra pelo numero de parcelas e utilizar pagamento recorrente?

**Comment by edson-nascimento** [comment]
```php
$sale = new Sale('123');
$customer = $sale->customer('Fulano de Tal');

//Passa o número de parcelas no 2° parametro ex 5x
$payment = $sale->payment(15700, 5);

// ou 
$payment->setInstallments(5);
```
Você só vai informar o **valor total da venda** e o número de parcelas e a cielo se encarrega de calcular o valor de cada parcela.

**Comment by rodrigomgrassioto** [comment]
certo.. muito obrigado pela prontidão.. vou testar
