### ISSUE TITLE
Evitar cartões tokenizados iguais

### ISSUE THREAD

**Issue by bruno-silva5** [DeveloperCielo/API-3.0-PHP#218]
Prezados, tudo bem?

Estou realizando uma integração com a API Cielo ecommerce, e gostaria de saber como eu faria uma verificação para evitar que o mesmo cartão seja tokenizado novamente?
Por exemplo, quando o usuario cadastra um novo cartão, é retornado um token, e esse token eu salvo no meu banco de dados, para que na proxima vez, o usuário possa realizar uma compra escolhendo o cartao que foi salvo e inserindo apenas o código de seguranca. 

Porém, se quando ele fizer outra compra, e caso ele ADICIONAR novamente o mesmo cartão que ja foi tokenizado (ele tem a opção de selecionar um cartão salvo ou adicionar um novo), o mesmo ira gerar novamente outro token e sera armazenado no banco, como eu faria para poder haver uma verificacao e evitar que novamente seja tokenizado?

**Comment by edson-nascimento** [comment]
Se você estiver salvando os 4 últimos dígitos do cartão antes de adicionar um novo você pode fazer essa verificação.
Lembrando que os últimos 4 dígitos não são informações sensíveis que implicam em PCI e também serve para o cliente saber qual cartão esta salvo em seu sistema.

**Comment by bruno-silva5** [comment]
Sim, estou salvando os últimos 4 dígitos do cartão junto a bandeira, pelo que pesquisei isso não fere nenhuma regra PCI. 

Eu pensei nessa solução que você tinha comentando, o único porém que havia encontrado é que caso o usuário insira um cartão diferente com os mesmos dígitos finais de algum já cadastrado (probabilidade pequena disso ocorrer) ele iria tratar como repetido.

Mas não encontrei uma outra forma se não essa, irei por final implementar ela mesmo.

Obrigado pela ajuda, Edson.

**Comment by edson-nascimento** [comment]
Certo, vai ser muito raro de acontecer, mas infelizmente não impossível, uma outra possível solução seria gerar um hash md5 ou similar em cima de alguns dados do cartão ex: últimos 4 dígitos + data de vencimento e salva-lo tbm e ao adicionar um novo verificar se já existe

**Comment by bruno-silva5** [comment]
Certo, acho que essa seria mais viável!

Então, apenas para confirmar: ao salvar um cartão, busco pelos cartões deste usuário, percorro os mesmos verificando (após descriptografar) se o valor encriptografado salvo é igual com o atual recebido (novo cartão a ser cadastrado). E por final faço o tratamento. Correto?

**Comment by edson-nascimento** [comment]
Não, minha sugestão era você criar um novo campo na tabela que está salvando o cartão, pode chamar por exemplo card_hash e nesse campo pode colocar o md5 daquelas informações combinadas.
Aí antes de salvar um novo cartão é só gerar o hash dele e fazer uma busca no banco se retornar já existe se não salva.
Não há necessidade de descriptografar esse hash ele pode ser de mão única, só serve para verificação.

**Comment by bruno-silva5** [comment]
Agora sim ficou mais claro, beleza Edson, farei isto mesmo. 

Obrigado!
