### ISSUE TITLE
Erro not required variable

### ISSUE THREAD

**Issue by filippiR** [DeveloperCielo/API-3.0-PHP#224]
The variable status is not required on docs but geting error on sandbox

then send the sale it returns this message

Error converting value {null} to type 'System.Byte'. Path 'status', line 1, position 1120.

**Comment by edson-nascimento** [comment]
Estou tento erros parecidos desde sexta no sandbox
`Request Error Error converting value {null} to type 'System.Int64'. Path 'serviceTaxAmount', line 1, position 226., código: 999`

Parece que atualizaram e quebrou o sandbox, será que alguém vai corrigir isso?

**Comment by rodrigomgrassioto** [comment]
> Estou tento erros parecidos desde sexta no sandbox
> `Request Error Error converting value {null} to type 'System.Int64'. Path 'serviceTaxAmount', line 1, position 226., código: 999`
> 
> Parece que atualizaram e quebrou o sandbox, será que alguém vai corrigir isso?

O meu está igual o seu. O modo de produção está funcionando.

**Comment by rodrigomgrassioto** [comment]
> > Estou tento erros parecidos desde sexta no sandbox
> > `Request Error Error converting value {null} to type 'System.Int64'. Path 'serviceTaxAmount', line 1, position 226., código: 999`
> > Parece que atualizaram e quebrou o sandbox, será que alguém vai corrigir isso?
> 
> O meu está igual o seu. O modo de produção está funcionando.

Voltou a funcionar hoje.

**Comment by filippiR** [comment]
Voltou a funcionar corretamente vou fechar o ticket!
