### ISSUE TITLE
Problema com composer, namespace...

### ISSUE THREAD

**Issue by 7evenbr** [DeveloperCielo/API-3.0-PHP#24]
Olá, ao executar a página tenho o seguinte erro:
Fatal error: Class 'Cielo\API30\Ecommerce\Environment' not found in /

Pode me ajudar?

**Comment by igorctb** [comment]
Comigo acontece a mesma coisa

**Comment by netojoaobatista** [comment]
Estão instalando as dependências com `composer install`? Se estiverem, basta fazer:

```php
<?php
require 'vendor/autoload.php';

//...
```

**Comment by igorctb** [comment]
Sim instalei com o composer install

**Comment by grupov43** [comment]
Pessoal , tive o mesmo problema 
fiz o download do codigo , fiz o upload pro meu server, assim que chamo o codigo disponivel tenho o mesmo problema , composer está instalado vendor definido no index . conseguiram entender esse erro ?

**Comment by netojoaobatista** [comment]
Pessoal, não é um erro; vocês precisam fazer `composer install` e, em seguida, incluir o `autoload.php` em seu código.

**Comment by grupov43** [comment]
já esta feito amigo , veja se estou fazendo da forma correta ! 

estou chando o php que foi postado aqui , a unica alteração que fiz foi apontar o autoload para meu folder que está ok , e um upgrade de php para 5.6 e tambem colocar meus IDs e KEY do sandbox para fazer um teste 

<?php
require 'vendor/autoload.php';

use Cielo\API30\Merchant;

use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;

use Cielo\API30\Ecommerce\Request\CieloRequestException;
// ...
// Configure o ambiente
$environment = $environment = Environment::sandbox();

// Configure seu merchant
$merchant = new Merchant('MERCHANT ID', 'MERCHANT KEY');

// Crie uma instância de Sale informando o ID do pagamento
$sale = new Sale('123');

// Crie uma instância de Customer informando o nome do cliente
$customer = $sale->customer('Fulano de Tal');

// Crie uma instância de Payment informando o valor do pagamento
$payment = $sale->payment(15700);

// Crie uma instância de Credit Card utilizando os dados de teste
// esses dados estão disponíveis no manual de integração
$payment->setType(Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");

// Crie o pagamento na Cielo
try {
    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

    // Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
    // dados retornados pela Cielo
    $paymentId = $sale->getPayment()->getPaymentId();

    // Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
    $sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);

    // E também podemos fazer seu cancelamento, se for o caso
    $sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);
} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}

?>

**Comment by grupov43** [comment]
estou chamando dessa forma ! 


						  $scope.url = 'http://blablabla.com.br/cielo/creditos.php';  
			  		$http.post($scope.url).success(function(all) 
						{
                            $scope.status = all;
                          			                         
							toastr.success('OK!', {progressBar: true, timeOut: '500'});
							console.log ($scope.status);
			
					
                         });

**Comment by grupov43** [comment]
<b>Fatal error</b>:  Class 'Ecommerce\Environment' not found in <b>/home/public_html/cielo/creditos.php</b> on line <b>14</b><br />


linha 14 -> $environment = $environment = Environment::sandbox();


declarações

<?php
require '../vendor/autoload.php';


use Ecommerce\Environment;
use Ecommerce\Sale;
use Ecommerce\CieloEcommerce;
use Ecommerce\Payment;

use Cielo\API30\Ecommerce\Request\CieloRequestException;

**Comment by netojoaobatista** [comment]
>  a unica alteração que fiz foi apontar o autoload para meu folder que está ok 

Esse é o ponto; seu autoload não está okay. Você deve ou adequar seu autoload para carregar o SDK corretamente, ou utilizar o autoload gerado corretamente pelo composer.

**Comment by grupov43** [comment]
voce consegue me passar os passos disso ?

**Comment by netojoaobatista** [comment]
1. `composer install`
2. `require 'autoload/vendor.php';`

:smile:

**Comment by grupov43** [comment]
eu consegui um acesso ssh ao meu server , agora faz mais sentido o que esta dizendo rs rs !!! 

ao inves do download e upload de um autoload pronto ...eu instalei o composer no meu server via linha de comando e agora usando o composer.json vou executar o composer install 
obrigado !

**Comment by netojoaobatista** [comment]
Exato!!!!

:smile:

**Comment by igorctb** [comment]
Olá, eu fiz o composer install e coloquei na minha pagina o

require 'vendor/autoload.php';

E ainda assim aparece o erro abiaxo: 

PHP Fatal error:  Class 'Cielo\API30\Ecommerce\Environment' not found in /home/###/public_html/cadastro/Cielo/processa_pagamento_cielo30.php on line 44
