### ISSUE TITLE
Erro ao configurar o SDK com seu merchant e o ambiente apropriado para criar a venda

### ISSUE THREAD

**Issue by ludero** [DeveloperCielo/API-3.0-PHP#25]
Pessoal, estou com dificuldades em encontrar o problema.
Utilizo o APTANA como IDE e nele aponta o erro nas seguintes linhas:
$sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);
$sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);
$sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);

Justamente onde está o -> aponta como erro de sintaxe e debugando e nesta linha o código para de executar.

Não sei o motivo.

Por favor, alguém passou dificuldade com as mesmas linhas?

**Comment by netojoaobatista** [comment]
Você precisa estar usando o PHP >= 5.6.

**Comment by ludero** [comment]
O erro estava na linha $environment = $environment = Environment::sandbox();
Troquei por esta e funcionou:
$environment = Environment::sandbox();

Encontrei a solução em um post já encerrado.
Parece que a pessoa não comitou a modificação.

Obrigado pela ajuda netojoaobatista.
