### ISSUE TITLE
Boleto ambiente de testes

### ISSUE THREAD

**Issue by ludero** [DeveloperCielo/API-3.0-PHP#26]
Pessoal, alguém já tentou fazer um boleto de testes?

Retorna o erro 310.

Fiz as modificações necessárias para enviar os parâmetros conforme o manual:
    $payment->setType(Payment::PAYMENTTYPE_BOLETO)
            ->setProvider(Payment::PROVIDER_BANCO_DO_BRASIL)
            ->setBoletoNumber("123");

mas nada até agora.

Abraço

**Comment by ludero** [comment]
Está funcionando.
Mandei imprimir a resposta e veio o boleto de teste perfeitamente.
Agora do retorno 310 eu já não sei.

**Comment by ludero** [comment]
Resposta do retorno 310:
Operação com boleto não deve-se utilizar $sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 'valor', 0);

**Comment by jozephbrasil** [comment]
Galera, vocês sabem informar qual o custo da utilização do boleto via Cielo? O boleto é com ou sem registro?

**Comment by jozephbrasil** [comment]
Como funcionária o "retorno" usando via Cielo?

**Comment by ludero** [comment]
Creio que vai continuar do mesmo jeito.
Emitir o boleto e dar baixa automática pelo BackOffice mesmo sendo registrado.
