### ISSUE TITLE
Números cartão simulado

### ISSUE THREAD

**Issue by andersonfelizari** [DeveloperCielo/API-3.0-PHP#29]
Boa noite

Na documentação consta vários números de cartões simulados para testes. Mais todos estão retornando como validos e retornando o ID do pagamento corretamente.

Testei o 0000.0000.0000.0002 , 0000.0000.0000.0009 e o 0000.0000.0000.0007 por exemplo.

Grato

**Comment by loja5combr** [comment]
Geralmente uso 1234123412341231 que para mim foi o único qual encontrei que aprova em modo de teste.
