### ISSUE TITLE
Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2'

### ISSUE THREAD

**Issue by deyvisonbrandao** [DeveloperCielo/API-3.0-PHP#31]
Boa Tarde,

Ao tentar efetuar uma transação, é retornado a seguinte mensagem: "Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2'", no qual não consegui identificar o motivo do falha na transação. Podem me ajudar?

**Comment by netojoaobatista** [comment]
Você precisa atualizar seu PHP.; a integração tem o TLS 1.2 como requisito. Segundo o manual do PHP, as versões mínimas são:

> CURL_SSLVERSION_TLSv1_2 (integer)
> Disponível a partir do PHP 5.5.19 e 5.6.3

**Comment by alexsmonte** [comment]
@netojoaobatista não há possibilidade de usar as versões PHP 5.5.19 e 5.6.3, estou usando a versão 5.6.18 existe alguma solução?

**Comment by netojoaobatista** [comment]
@alexsmonte, se você estiver com o openssl >= 1.0.1, então você pode tentar fazer a integração manualmente, sem o SDK, utilizando o inteiro `6` no lugar da constante `CURL_SSLVERSION_TLSv1_2`.

**Comment by giovannylisboa** [comment]
olá, @netojoaobatista . Estou tendo o mesmo problema, mas o estranho é que o meu php é o 5.6.30. Pode ser algum outro problema??

**Comment by francorafael** [comment]
O @netojoaobatista Citou uma opção eu testei e deu certo @giovannylisboa 

O arquivo fica vendor\developercielo\api-3.0-php\src\Cielo\API30\Ecommerce\Request
AbstractSaleRequest.php linha 34

"utilizando o inteiro 6 no lugar da constante CURL_SSLVERSION_TLSv1_2."

//curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
curl_setopt($curl, CURLOPT_SSLVERSION, 6);

**Comment by netojoaobatista** [comment]
Caso queira utilizar o SDK e não tenha a constante por qualquer motivo, basta fazer assim na sua index, config ou antes de utilizar o SDK:

```php
if (!defined('CURL_SSLVERSION_TLSv1_2')) {
   define('CURL_SSLVERSION_TLSv1_2', 6);
}
```

Isso faz o seguinte: se a constante `CURL_SSLVERSION_TLSv1_2` não estiver definida, defina-a com o valor 6. Fazendo isso, tudo vai funcionar automagicamente.

:D

**Comment by carcleo** [comment]
Estou tentando um acesso via SANDBOX com o seguinte código exemplo enconttado no Manual de Integração:

<?php

header( 'Content-Type: application/json' );

require_once "_global/_erros/erros.ini";

$linkSite = "http://www.hotplateprensas.com.br";

$dados = array( 
"MerchantId" => "8292b0f0-d43a-194a-bc2c-3906d12f581b", 
"MerchantKey" => "OIXSJWFWZLNKUJOABCSXUQETLWDPFWLNLHENRTNI", 
"MerchantOrderId" => "1", 
"Authenticate" => true, 
"sandbox" => true, // Opcional - Ambiente de Testes 
"debug" => true, // Opcional - Exibe os dados enviados na requisição para a Cielo 
"Customer" => array( 
"Name" => "Comprador crédito completo", 
"Email" => "compradorteste@teste.com", 
"Birthdate" => "1991-01-02", 
"Address" => array( 
"Street" => "Rua Teste", 
"Number" => "123", 
"Complement" => "AP 123", 
"ZipCode" => "12345987", 
"City" => "Rio de Janeiro", 
"State" => "RJ", 
"Country" => "BRA" 
), 
"DeliveryAddress" => array( 
"Street" => "Rua Teste", 
"Number" => "123", 
"Complement" => "AP 123", 
"ZipCode" => "12345987", 
"City" => "Rio de Janeiro", 
"State" => "RJ", 
"Country" => "BRA" 
) 
), 
"Payment" => array( 
"Type" => "CreditCard", 
"Amount" => 15700, 
"Currency" => "BRL", 
"Country" => "BRA", 
"ServiceTaxAmount" => 0, 
"Installments" => 1, 
"Interest" => "ByMerchant", 
"Capture" => true, 
"Authenticate" => false, 
"ReturnUrl" => $linkSite . "/retornoCielo.php", 
"SoftDescriptor" => "123456789ABCD", 
"CreditCard" => array( 
"CardNumber" => "1234123412341231", 
"Holder" => "Teste Holder", 
"ExpirationDate" => "12/2030", 
"SecurityCode" => "123", 
"SaveCard" => "false", 
"Brand" => "Visa" 
) 
),

);

$urlProducaoR = "https://api.cieloecommerce.cielo.com.br/"; 
$urlSandboxR = "https://apisandbox.cieloecommerce.cielo.com.br"; 
$urlSandboxC = "https://apiquerysandbox.cieloecommerce.cielo.com.br/";

$ch = curl_init();

curl_setopt( $ch, CURLOPT_URL, $urlSandboxR ); 
curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $dados ) ); 
curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, "POST" );

$urlSSL = $linkSite . "/ssl/Root.crt";

curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true ); 
curl_setopt( $ch, CURLOPT_CAINFO, $urlSSL ); 
curl_setopt( $ch, CURLOPT_SSLVERSION, 4 ); 
curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, true ); 
curl_setopt( $ch, CURLOPT_SSL_VERIFYHOST, 2 );

$result = curl_exec( $ch ); 
$erro = curl_error( $ch ); 
$info = curl_getinfo( $ch );

print "<pre>"; 
print_r( $result ); 
print_r( $erro ); 
print_r( $info ); 
print "</pre>";

// Fecho a conexão 
curl_close( $ch );

?>

print_r( $result ) Retorna vazio

print_r( $erro ) Retorna o erro abaixo 
error setting certificate verify locations: 
CAfile: http://www.hotplateprensas.com.br/ssl/Root.crt 
CApath: none 

print_r( $info ) Retorna a saída abaixo:

Array 
( 
[url] => https://apisandbox.cieloecommerce.cielo.com.br/ 
[content_type] => 
[http_code] => 0 
[header_size] => 0 
[request_size] => 0 
[filetime] => -1 
[ssl_verify_result] => 1 
[redirect_count] => 0 
[total_time] => 11.719 
[namelookup_time] => 11.531 
[connect_time] => 11.719 
[pretransfer_time] => 0 
[size_upload] => 0 
[size_download] => 0 
[speed_download] => 0 
[speed_upload] => 0 
[download_content_length] => -1 
[upload_content_length] => -1 
[starttransfer_time] => 0 
[redirect_time] => 0 
[redirect_url] => 
[primary_ip] => 52.171.57.12 
[certinfo] => Array 
( 
)

[primary_port] => 443 
[local_ip] => 192.168.1.4 
[local_port] => 58548 
)

Onde estou errando?
