### ISSUE TITLE
Como vizualizar retorno cielo

### ISSUE THREAD

**Issue by grupov43** [DeveloperCielo/API-3.0-PHP#33]

**Comment by grupov43** [comment]
Meu post esta indo dessa maneira , 

$scope.pago = function() {

				    $scope.url = 'http://dominio/src/creditos.php';  
			  		$http.post($scope.url).success(function(a){
  					console.log(a);
	
					
					})
					.error(function(err){
  					console.log(err);
					})
-----------------------

creditos . php é exatamente o que esta disponivel no site ...  

<?php
require '../vendor/autoload.php';

use Cielo\API30\Merchant;

use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;

use Cielo\API30\Ecommerce\Request\CieloRequestException;
// ...
// Configure o ambiente
$environment = $environment = Environment::sandbox();

// Configure seu merchant
$merchant = new Merchant('71541dfa-aba1-4a00-bc4d-57e6efea2696', 'VFEUFOFVQIXIQQKEDHMODRFGMTRSGQUJKJHIVXFT');

// Crie uma instância de Sale informando o ID do pagamento
$sale = new Sale('123');

// Crie uma instância de Customer informando o nome do cliente
$customer = $sale->customer('Fulano de Tal');

// Crie uma instância de Payment informando o valor do pagamento
$payment = $sale->payment(15700);

// Crie uma instância de Credit Card utilizando os dados de teste
// esses dados estão disponíveis no manual de integração
$payment->setType(Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");

// Crie o pagamento na Cielo
try {
    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

    // Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
    // dados retornados pela Cielo
    $paymentId = $sale->getPayment()->getPaymentId();

    // Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
    $sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);

    // E também podemos fazer seu cancelamento, se for o caso
  //  $sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);
} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}

**Comment by grupov43** [comment]
como pego o retorno da cielo para saber a aprovação ou nao !

**Comment by grupov43** [comment]
Retorno ! 
```
200
scripts.8b0f78c5.js:1 function (name){if(headersObj||(headersObj=parseHeaders(headers)),name){var value=headersObj[lowercase(name)];return void 0===value&&(value=null),value}return headersObj}
scripts.8b0f78c5.js:1 
```

**Comment by netojoaobatista** [comment]
Se seu `creditos.php` é o exemplo do [README.md](https://github.com/DeveloperCielo/API-3.0-PHP/blob/master/README.md#criando-um-pagamento-com-cartão-de-crédito), então você tem o `paymentId` e o `tid` em caso de sucesso e pode pegar o retorno da autorização através dos `returnCode` e `returnMessage`:

```php
// ...
$sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

$payment = $sale->getPayment();
$returnCode = $payment->getReturnCode();
$paymentId = $payment->getPaymentId();
$tid = $payment->getTid();
//...
```

[A lista com os códigos de retorno você encontra no manual](https://developercielo.github.io/Webservice-3.0/#códigos-de-retorno-das-vendas).

**Comment by grupov43** [comment]
perfeito , Obrigado !
