### ISSUE TITLE
Problema no composer

### ISSUE THREAD

**Issue by igorctb** [DeveloperCielo/API-3.0-PHP#34]
Olá, eu fiz o composer install e coloquei na minha pagina: 

require 'vendor/autoload.php';

E ainda assim aparece o erro abiaxo:

PHP Fatal error: Class 'Cielo\API30\Ecommerce\Environment' not found in /home/###/public_html/cadastro/Cielo/processa_pagamento_cielo30.php on line 44

O que estou fazendo de errado ?

**Comment by netojoaobatista** [comment]
Faça o seguinte:

1. Abra seu terminal;
2. Crie um diretório aleatório em algum lugar da sua máquina;
3. Entre no diretório recém criado e execute: `composer require "developercielo/api-3.0-php"`;
4. Execute: `php -r "require 'vendor/autoload.php'; echo Cielo\API30\Ecommerce\Environment::sandbox()->getApiUrl() . PHP_EOL;"`

Qual foi a saída?

**Comment by igorctb** [comment]
root@server [/home/###/public_html/cadastro/teste]#
root@server [/home/###/public_html/cadastro/teste]# php -r "require 'vendor/autoload.php';
> echo Cielo\API30\Ecommerce\Environment::sandbox()->getApiUrl() . PHP_EOL;"
https://apisandbox.cieloecommerce.cielo.com.br/

**Comment by netojoaobatista** [comment]
Então sabemos que o composer está okay e que o SDK está perfeito. O problema está no seu código aí; está seguindo a [PSR-0](http://www.php-fig.org/psr/psr-0/) ou a [PSR-4](http://www.php-fig.org/psr/psr-4/)?

**Comment by igorctb** [comment]
Olá

Meu código é o mesmo que esta no exemplo

require_once(__DIR__ . "/vendor/autoload.php");
//require 'vendor/autoload.php';

use Cielo\API30\Merchant;
use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;
use Cielo\API30\Ecommerce\Request\CieloRequestException;
// ...

// Configure o ambiente
$environment = $environment = Environment::sandbox();

// Configure seu merchant

$merchant = new Merchant('####', '####');

// Crie uma instância de Sale informando o ID do pagamento

$sale = new Sale($transacao);

// Crie uma instância de Customer informando o nome do cliente

$customer = $sale->customer($cartaoTitular);

// Crie uma instância de Payment informando o valor do pagamento

$payment = $sale->payment($valorPedido);

// Crie uma instância de Credit Card utilizando os dados de teste
// esses dados estão disponíveis no manual de integração

$payment->setType(Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard($cartaoNumero, $codigoBandeira)
        ->setExpirationDate($cartaoValidade)
        ->setCardNumber($cartaoNumero)
        ->setHolder($cartaoTitular);
// Crie o pagamento na Cielo
try {
    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

    // Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
    // dados retornados pela Cielo
    $paymentId = $sale->getPayment()->getPaymentId();

    print_r($paymentId);

    // Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
    $sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, $valorPedido, 0);

    // E também podemos fazer seu cancelamento, se for o caso
    $sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, $valorPedido);

} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}

**Comment by netojoaobatista** [comment]
> Meu código é o mesmo que esta no exemplo

Não é não; você mudou o fragmento que carrega o autoload; o que é esse DIR aí?

Btw, como está sua estrutura de diretórios?

**Comment by igorctb** [comment]
Esta assim

/home/###/public_html/cadastro/Cielo/processa_pagamento_cielo30.php -> pagina do código
/home/###/public_html/cadastro/Cielo/src/API30/Environment.php
/home/###/public_html/cadastro/Cielo/vendor/autoload.php

**Comment by netojoaobatista** [comment]
O que é esse `/home/###/public_html/cadastro/Cielo/src/API30/Environment.php`? Onde estão seu `composer.json` e `composer.lock`?

**Comment by igorctb** [comment]
Estão aqui:
/home/###/public_html/cadastro/Cielo/composer.json
/home/###/public_html/cadastro/Cielo/composer.lock

Já este aqui -> /home/###/public_html/cadastro/Cielo/src/API30/Environment.php

é o arquivo que veio junto quando baixei o API-3.0-PHP no github

**Comment by netojoaobatista** [comment]
Cara, é impossível você ter instalado o SDK via composer e sua estrutura de diretórios estar dessa forma. 

Instale o pacote via composer como já explicado, que seu código irá funcionar:

1. Instale via composer;
    1. Se já tiver um `composer.json`, faça `composer install`;
    2. Se seu projeto não tiver um `composer.json`, faça `composer require "developercielo/api-3.0-php"`;
2. Implemente sua integração conforme exemplificado no `README.md`;
3. Execute.

É importante que você faça a instalação **exatamente** como acima; é fundamental que não modifique os arquivos de lugar nem que mude o carregamento do autoload do composer. Se você fizer modificações, aí não consigo ajudá-lo com seu código.

**Comment by igorctb** [comment]
Consegui, instalei novamente e funcionou, mais agora esta apresentando o seguinte erro:

[18-Apr-2017 13:46:52 America/New_York] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Curl error: SSL: no alternative certificate subject name matches target host name 'apisandbox.cieloecommerce.cielo.com.br'' in /home/###/public_html/cadastro/teste/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php:62
Stack trace:
#0 /home/###/public_html/cadastro/teste/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/CreateSaleRequest.php(25): Cielo\API30\Ecommerce\Request\AbstractSaleRequest->sendRequest('POST', 'https://apisand...', Object(Cielo\API30\Ecommerce\Sale))
#1 /home/###/public_html/cadastro/teste/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(57): Cielo\API30\Ecommerce\Request\CreateSaleRequest->execute(Object(Cielo\API30\Ecommerce\Sale))
#2 /home/###/public_html/cadastro/Cielo/processa_pagamento_cielo30.php(73): Cielo\API30\Ecommerce\CieloEcommerce->createSale(Object(Cielo\API30\Ecommerce\Sale))
#3 {main}
  thrown in /home/###/public_html/cadastro/teste/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php on line 62

**Comment by netojoaobatista** [comment]
Instale os certificados [como descrito aqui](https://developercielo.github.io/Webservice-3.0/#como-instalar-o-certificado-extended-validation-no-servidor-da-loja?)

**Comment by igorctb** [comment]
funcionou, mais agora aparece o seguinte erro:

Cielo\API30\Ecommerce\Request\CieloError Object ( [code:Cielo\API30\Ecommerce\Request\CieloError:private] => 146 [message:Cielo\API30\Ecommerce\Request\CieloError:private] => SecurityCode length exceeded )

**Comment by netojoaobatista** [comment]
Você encontra a tabela dos [Códigos de Erros](https://developercielo.github.io/Webservice-3.0/#códigos-de-erros-da-api) no manual da API.

**Comment by igorctb** [comment]
Nossa consegui. Obrigado pela ajuda. Última pergunta, como faço para mostrar na tela o xml de retorno da transação ?

**Comment by netojoaobatista** [comment]
> como faço para mostrar na tela o xml de retorno da transação ?

Não tem XML nessa integração. A API trafega JSON, que está encapsulado no SDK, que já faz todo o tratamento; não existe a opção de mostrar um dump do JSON via SDK.

**Comment by Lutex** [comment]
Estou tendo o mesmo problema com o certificado SSL, fiz todo o procedimento de importação dos arquivos .crt disponíveis no site da Cielo Dev, porem continuo recebendo o erro:

Arquivos importados: 
Root.crt
Intermediate1.crt
Intermediate2.crt

Fatal error: Uncaught exception 'RuntimeException' with message 'Curl error: SSL certificate problem: unable to get local issuer certificate' .....

Como devo proceder ?



![2018-02-20_09-55-05](https://user-images.githubusercontent.com/774798/36425090-6d53999a-1624-11e8-9638-3ecec5529e01.jpg)
