### ISSUE TITLE
Exemplo Pagamento por boleto e transferencia

### ISSUE THREAD

**Issue by igorctb** [DeveloperCielo/API-3.0-PHP#38]
Olá podem dar um exemplo de código para fazer vendas por boleto e transferência bradesco

**Comment by davicrystal** [comment]
Analisando o código acredito que apesar de mencionado no Readme.md a transferência e boleto não estão implementados no código desse SDK, confirma @netojoaobatista ?

**Comment by jhernandes** [comment]
Estou tentando utilizar o SDK para criar Payments de Boleto, mas acaba que o preenchimento do boleto não está completo (falta o District).

Em Payment falta algumas informações:

 "Assignor": "Empresa Teste",
 "Demonstrative": "Desmonstrative Teste",
 "ExpirationDate": "5/1/2015",
 "Identification": "11884926754",
 "Instructions": "Aceitar somente até a data de vencimento, após essa data juros de 1% dia."

http://developercielo.github.io/Webservice-3.0/?json#criando-uma-venda-de-boleto

**Comment by netojoaobatista** [comment]
Adicionei o suporte e um exemplo em https://github.com/DeveloperCielo/API-3.0-PHP/commit/93ab2dbb85ba9c8458304c1113deaf833d981447
