### ISSUE TITLE
Disponibilização via composer

### ISSUE THREAD

**Issue by mozgbrasil** [DeveloperCielo/API-3.0-PHP#4]
Ola

Boa Tarde

Tudo bom meus amigos

Tenho interesse no uso do SDK mas vemos que o mesmo não se encontra registrado no packagist

https://packagist.org/packages/developercielo/

Impossibilitando o uso da biblioteca

**Comment by netojoaobatista** [comment]
`composer require "developercielo/api-3.0-php:dev-master"`
