### ISSUE TITLE
your manual is a joke

### ISSUE THREAD

**Issue by memobr** [DeveloperCielo/API-3.0-PHP#41]
very bad documentation doesn't have one example code.

**Comment by netojoaobatista** [comment]
Take a look at the [README.md](https://github.com/DeveloperCielo/API-3.0-PHP/blob/master/README.md))? There are some code samples in there.

**Comment by devjgwebcom** [comment]
Então, no <a href="https://developercielo.github.io/Webservice-3.0/">manual</a> algumas referências estão erradas, o item do menu ativo não condiz com o conteúdo exibido.
E em Capturando uma venda, está digitado errado a frase: "Para captura uma venda que utilizaou cartão de crédito, é necessário fazer um PUT para o recurso Payment conforme o exemplo."
