### ISSUE TITLE
Pagamento Recorrente

### ISSUE THREAD

**Issue by cleitonalbino** [DeveloperCielo/API-3.0-PHP#42]
@netojoaobatista poderia postar um exemplo de uma criação de venda recorrente..

**Comment by cleitonalbino** [comment]
Consegui, fiz da seguinte forma:
```php
require '../../vendor/API-3.0-PHP-master/vendor/autoload.php';


use Cielo\API30\Merchant;

use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;
use Cielo\API30\Ecommerce\CreditCard;
use Cielo\API30\Ecommerce\Customer;
use Cielo\API30\Ecommerce\RecurrentPayment;

$environment = $environment = Environment::sandbox();

$merchant = new Merchant($merchantID, $merchantKey);

$creditCard = new CreditCard();
$recurrent = new RecurrentPayment();
$customer = new Customer();
$payment = new Payment();
$sale = new Sale();


$recurrent = $recurrent->setInterval('Monthly')->setAuthorizeNow(true);

$creditCard = $creditCard->setBrand($brand)
   ->setExpirationDate($month."/".$year)
   ->setCardNumber($ccNumber)
   ->setSecurityCode($cvc)
   ->setHolder($name);

$payment = $payment->setAmount(49000)
   ->setSoftDescriptor('MYPROJECT')
   ->setInstallments(1)
   ->setType("CreditCard")
   ->setRecurrentPayment($recurrent)
   ->setCreditCard($creditCard);

$customer = $customer->setName($name);

$sale = $sale->setPayment($payment)
   ->setMerchantOrderId('123')
   ->setCustomer($customer);

try {
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);
    $paymentID = $sale->getPayment()->getPaymentId();
    $paymentTID = $sale->getPayment()->getTid();
    $getRecurrentPayment = $sale->getPayment()->getRecurrentPayment();
    $capture = (new CieloEcommerce($merchant, $environment))->captureSale($paymentID, 49000, 0);
	var_dump($sale);
	
} catch (CieloRequestException $e) {
	$error = $e->getCieloError();
}

```

**Comment by marcelo2605** [comment]
@cleitonalbino Estou tendo problemas com a modalidade recorrente. Usando o exemplo do README, retorna um erro para a linha `$recurrent = $recurrent->setInterval(RecurrentPayment::INTERVAL_MONTHLY)
                        ->setAuthorizeNow(true);`.

Agora testei o seu, mas ele retorna NULL para o `$paymentID`.

**Comment by cleitonalbino** [comment]
Olá @marcelo2605 dei uma olhada no README e existe um erro, @netojoaobatista esqueceu de chamar a classe ``RecurrentPayment``, o php da erro porque ele não reconhece a variavel $recurrent, usando o README como exemplo coloque o seguinte código: ``$recurrent = new RecurrentPayment();``, e vê se da certo, no meu ele dá algum erro na transação?

**Comment by marcelo2605** [comment]
@cleitonalbino Maravilha. O erro foi corrigido. Agora o problema é o seguinte: após rodar o `createSale()`, eu pego o status usando `$sale->getPayment()->getStatus()` para verificar se posso ou não fazer a captura. Mas ele está retornando 0. Você tem idéia o que pode ser?
