### ISSUE TITLE
API retorna mensagem de erro errada (MerchantId is Required)

### ISSUE THREAD

**Issue by andresams** [DeveloperCielo/API-3.0-PHP#44]
Encontrei hoje mais dois problemas com a API da Cielo. Ela retorna o erro 101 (MerchantId is Required) no ambiente de produção quando o CVV não é informado. Um exemplo:

https://apiquery.cieloecommerce.cielo.com.br/1/sales/9dc67d5d-6241-45b6-a3d5-65847fea7c6c

O segundo problema é que na Sandbox, quando o CVV não é informado, ele retorna que a transação foi completada com sucesso.

Só descobri isso ligando no 0800 para saber o porquê de as transações não estarem sendo aprovadas.  O CVV não estava sendo enviado devido a um erro de digitação do nome do campo.

O mais interessante é que, mesmo com este problema, homologaram a conta. Ou seja, quem está fazendo a homologação na verdade está fingindo que está fazendo. Já que é para liberar de qualquer jeito, que tivessem me liberado antes ao invés de ter me feito esperar 15 dias.

Cielo decaindo mais a cada dia. Só não perdem mercado porque os concorrentes são ainda mais incompetentes.

Estou deixando o tópico aqui para quem tiver o mesmo problema e procurar no Google.

**Comment by frekele** [comment]
@andresams 

Concordo em parte, pois o CVV deveria ser obrigatório tanto em sandbox quando em production.
Porem o anbiente sandbox, é uma simulação, então alguns campos acabam sendo permitidos por necessidade, para facilitar os testes do desenvolvedor.

Já no argumento sobre a qualidade decaindo, acredito que em alguns pontos a qualidade está a desejar mesmo, porem a Cielo tem uma estrutura inovadora, onde nem a concorrência tem igual, então como eles "teoricamente" são os primeiros nesse campo aqui no BR, (como a Cielo Lio), devemos dar um desconto a eles, pelo fato do trabalho dobrado que devem estar tendo.

Abraços
