### ISSUE TITLE
Captura automática não ocorre para cartões de débito

### ISSUE THREAD

**Issue by davicrystal** [DeveloperCielo/API-3.0-PHP#47]
Mesmo definindo a captura automática como **"true"** a mesma não ocorre para pagamentos via cartão de débito, sempre necessito realizar a captura "manual" posteriormente, conforme exemplo:

```
$objPayment` = $objSale->payment(10000, 1)
->setCapture(true)
->setAuthenticate(true);
```
...

```
$objPayment->debitCard(123, 'Visa')
->setExpirationDate('12/2019')
->setCardNumber('0000000000000001')
->setHolder('Mr Foo');
```

Trata-se de uma característica da API 3.0, problema do SDK ou algo que estou fazendo errado?

Obs.: Pagamentos via crédito, a captura automática ocorre normalmente.

**Comment by netojoaobatista** [comment]
Não existe captura posterior no débito; por definição, toda transação com débito tem captura automática.

**Comment by davicrystal** [comment]
Olá @netojoaobatista 

Se toda transação a débito tem a captura automática porque  quando consulto uma transação a débito tenho sempre o retorno status **(1)** , que segundo o manual https://developercielo.github.io/Webservice-3.0/#status---status-de-uma-transação indica  **"Autorizado - Meio de pagamento apto a ser capturado ou pago(Boleto)"**? 

_Exemplo do retorno da consulta de uma transação débito em ambiente de testes:_

STATUS: (1) - Autorizado - Meio de pagamento apto a ser capturado ou pago(Boleto)
TYPE: DebitCard 
TID: 0524115158666
PAYMMENT ID: 4a8f1ee4-8296-4257-b473-524144b26963 
AUTORIZATION CODE: 530252 
AUTORIZATION DATE: 2017-05-24 11:51:58

Vou além, quando realizo o processo de captura dessa transação **a débito**, tenho sucesso na solicitação e então o status da mesma transação é alterado para **2** que no manual indica ser  **(2) - Pagamento Confirmado - Pagamento confirmado e finalizado**

No Aguardo
