### ISSUE TITLE
Cancelamento/Estorno da venda

### ISSUE THREAD

**Issue by matheus-jg-dev** [DeveloperCielo/API-3.0-PHP#50]
Olá
Estou executando esse código abaixo:
```
// E também podemos fazer seu cancelamento, se for o caso
$sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, $amount);
```
Sempre retorna o status da transação como 10 - Cancelado
Porém na documentação [https://developercielo.github.io/Webservice-3.0/#status---status-de-uma-transação](https://developercielo.github.io/Webservice-3.0/#status---status-de-uma-transação) está como:
- 10 Cancelado
- 11 Cancelado/Estornado

A minha dúvida é: 
**Ao executar o cancelamento da venda, o estorno é automático ou é necessário executar outro método para ocorrer o estorno da venda?**

Grato,

**Comment by LuDdk** [comment]
Também estou com esta duvida.
Grato

**Comment by netojoaobatista** [comment]
Cancelamento ou estorno são a mesma operação; o que ocorre é que o cancelamento ocorre antes da captura e o estorno, depois. Se a venda tiver sido realizada com autorização e captura automática, então ocorrerá o cancelamento, se for executado antes da captura.

:smile:

**Comment by Akira-ux** [comment]
Boa noite, poderia me esclarecer uma duvida de como eu recupero os dados somente enviando o cancelamento?

Estou realizando o cancelamento assim pela API.

        $environment = Environment::sandbox();
       $merchant = new Merchant('MERCHANT ID', 'MERCHANT KEY');

        $paymentId = 'payment';
        $amount = 'valor';

        try {
            $sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId,$amount);
           //e como que eu recupero os dados do $sale igual quando realiza uma compra ex: $payment->getPaymentId
        } catch (CieloRequestException $e) {
             $x = $e->getCieloError(); // minha duvida é como que eu acesso isso separado para passar em variavel
            $error = $e->getCode(); // aqui ele não me retorna o verdadeiro Code que retorna no getCieloError().
            $mensagem = $e->getMessage();  // aqui ele não me retorna a verdadeira mensagem que retorna no getCieloError().
        }
