### ISSUE TITLE
Problema com Composer

### ISSUE THREAD

**Issue by 7evenbr** [DeveloperCielo/API-3.0-PHP#58]
Olá, boa tarde.
Estou tendo alguns problemas na instalacao do composer. Estou com a aplicação na Locaweb. Usei essa referencia para instalacao do composer: https://ajuda.locaweb.com.br/pt-br/Composer

Após instalar, jogo o composer.json (presente nessa publicacao) no mesmo diretorio do composer.phar. Feito isso tento utilizar "composer install" e tambem "composer require "developercielo/api-3.0-php" e é retornado o seguinte erro: "composer: command not found".

Quando coloco o comando: "php56 -c ~/php.ini composer.phar install" me retorna um positivo:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

a pasta "vendor" é gerada, mas a Cielo não.... ai faço o download aqui no git e jogo no respectivo endereco. 

ao rodar o codigo de exemplo aqui informado é retornado o seguinte erro:
Fatal error: Class 'Cielo\API30\Ecommerce\Environment' not found in /home/storage/8/6e/54/arraialecoparque/public_html/ingresso/teste_pagamento.php on line 14

Essa pasta Cielo deveria ter sido criada automaticamente pelo composer? desculpe a ignorancia, mas é algo novo para mim.

Por favor, peço humildemente a sua ajuda, meu emprego está dependendo muito disso.

**Comment by netojoaobatista** [comment]
Você não deve utilizar o `composer.json` desse repositório porque ele diz respeito a esse repositório. Para utilizar em sua loja, você deve criar seu próprio `composer.json` com suas próprias dependências. Caso ainda não tenha um, faça o seguinte:

```shell
composer require "developercielo/api-3.0-php"
```

Isso vai criar o diretório `vendor` e, dentro dele, o `autoload.php` e o diretório `developercielo`. Com isso, basta carregar o `vendor/autoload.php`:

```php
<?php
require 'vendor/autoload.php';
//...
```

Todas as instruções de que precisa estào no [README.md] (https://github.com/DeveloperCielo/API-3.0-PHP/blob/master/README.md) do repositório.

**Comment by 7evenbr** [comment]
Ola Joao, boa tarde.

devo adicionar: composer require "developercielo/api-3.0-php" no meu proprio composer.json ou no terminal?

**Comment by netojoaobatista** [comment]
No terminal.

Agora, se você **já tiver** um `composer.json`, aí você só precisa executar `composer install` no seu terminal.

**Comment by 7evenbr** [comment]
Entendi. Eu já havia feito isso. Por favor, olha no print, retorna uma mensagem de erro. Será que é algo relacionado a Locaweb?

![captura de tela 2017-07-04 as 16 55 42](https://user-images.githubusercontent.com/22399502/27841659-b1db50b8-60d9-11e7-9934-b74a705ed535.png)

**Comment by netojoaobatista** [comment]
```shell
php composer.phar require "developercielo/api-3.0-php"
```

**Comment by 7evenbr** [comment]
Agora é retornado outro erro. Por favor, veja no print.
![captura de tela 2017-07-04 as 17 07 03](https://user-images.githubusercontent.com/22399502/27841901-4fe6fd56-60db-11e7-97fa-02810bdb663e.png)

**Comment by 7evenbr** [comment]
Consegui meu irmao, vc me deu uma luz.

Fiz assim: php56 -c ~/php.ini composer.phar require "developercielo/api-3.0-php" ai rolou.

Deus abençoe sua vida.
