### ISSUE TITLE
Cartão de Débito

### ISSUE THREAD

**Issue by fernandobandeira** [DeveloperCielo/API-3.0-PHP#6]
Como é feita a requisição para um cartão de débito?
Estou fazendo desta forma:

```php
$payment->creditCard(trim($request->cvv), trim($request->card))
		->setExpirationDate($request->expiration_month.'/20'.$request->expiration_year)
		->setCardNumber(trim($request->card_number))
		->setHolder($request->nome);

$payment->setType(Payment::PAYMENTTYPE_DEBITCARD)
		->setReturnUrl(route('loja.sucesso'));
```

Mas pelo que eu vi ele tá enviando o ``` type ``` como debitCard e um array com ``` creditCard ``` confere? No manual teria que enviar um array com um ``` debitCard ``` procurei e não tem método nem nada para isso, por isso fiquei na dúvida... Pelo que eu vi as outras SDK's estão com a lógica parecida...

**Comment by arturcesarmelo** [comment]
tive que modificar grotescamente a API que, bastante entristecido, percebo que é incompleta.

De fato vc precisa adicionar um atributo private $debitCard e setar o objeto creditCard nele para, no fim, ser serializado com o nome "debitCard" no json.

Já foi enviado um PR para a API com essa correção.

Aguardamos a atualização.

enquanto isso, vc terá que alterar isso manualmente.

**Comment by fernandobandeira** [comment]
Com o novo método adicionado pelo #7 a issue foi solucionada, porém adicionou um bug, olhar o #14 ,

Exemplo para uso:
```php
$payment->debitCard(trim($request->cvv), trim($request->card))
		->setExpirationDate($request->expiration_month.'/20'.$request->expiration_year)
		->setCardNumber(trim($request->card_number))
		->setHolder($request->nome);
```
