### ISSUE TITLE
Retorno do cartão de débito

### ISSUE THREAD

**Issue by marcelo2605** [DeveloperCielo/API-3.0-PHP#62]
Estou com dúvidas para implementar o pagamento com cartão de débito.

No momento, uso o modo sandbox. Depois que eu envio o usuário para a authenticationUrl e faço a autenticação, ele voltar para a url definida.

Neste retorno, a Cielo envia alguma informação que precisa ser checada? RetrunCode ou Status?

**Comment by jhonnymakis** [comment]
Sim, você tem que verificar se a compra foi aprovada pelo códigos 00 ou 000. 
Pois o usuário pode não ter autenticado no banco, pode ter demorado demais para autenticar e etc.
