### ISSUE TITLE
Cartao de Credito - Transaction not available to capture

### ISSUE THREAD

**Issue by ricktg** [DeveloperCielo/API-3.0-PHP#63]
Ola,

Tenho recebido somente esse erro (codigo 308) quanto tento capturar a venda.

Segui os passos do exemplo e só ocorre esse erro.

Alguma sugestão?

**Comment by netojoaobatista** [comment]
No manual, na seção [códigos de erros da api](https://developercielo.github.io/Webservice-3.0/#códigos-de-erros-da-api), há a descrição do erro:

CÓDIGO | MENSAGEM | DESCRIÇÃO
-- | -- | --
|308 | Transaction not available to capture | Transação não pode ser capturada - Entre em contato com o suporte Cielo

**Comment by ricktg** [comment]
Entrei em contato com eles e me pediram para postar uma pergunta aqui.

**Comment by duducosmos** [comment]
Alguma solução pra esse problema?

**Comment by fgnievinski** [comment]
No meu caso isso significava que o banco havia declinado o pagamento devido a limite excedido.

**Comment by caiomorozini** [comment]
O cartão precisa ser válido para realizar a captura, ou seja, o código de resposta da cielo precisa ser 4 ou 6 com mensagem "Operation Sucessful". Caso contrário, vai cair nesse código. Aqui estão alguns cartões e respostas que a cielo disponibiliza para sandbox: <https://developercielo.github.io/manual/cielo-ecommerce#cart%C3%A3o-de-cr%C3%A9dito-sandbox>
