### ISSUE TITLE
Dúvidas quanto a POST notification, alguém poderia soluciona-las?

### ISSUE THREAD

**Issue by felipe7229** [DeveloperCielo/API-3.0-PHP#76]
Boa tarde gente.
Foi cadastrado junto a cielo a url para receber as notificações sobre os status de uma venda. Entretanto não estou recebendo dado algum, tanto para captura quanto para cancelamento ou qualquer outro evento que sofra uma venda. Alguém utiliza esse recurso ? Por favor me deem uma ajuda

**Comment by netojoaobatista** [comment]
A requisição da notificação você recebe, mas não recebe os dados, é isso?

**Comment by felipe7229** [comment]
então neto, eu verifiquei com a CIELO, agora está chegando, porém demorava muito tempo para vir, exemplo, 3 horas.

**Comment by felipe7229** [comment]
Outra dúvida, não sei se você sabe me responder. As notificações que disparam quando um evento acontece na compra(e.g, cancelamento) vem sempre com ChangeType 1, que quer dizer mudança de status. Pensei que era parecido com o Gerencianet, que falava o que houve na compra.

**Comment by netojoaobatista** [comment]
Você recebe a informação que houve a mudança de status e faz a consulta para obter todos os dados da venda.

**Comment by netojoaobatista** [comment]
Pense assim: alguém descobriu a URL que processa as notificações e envia um POST com alguns dados. Como você sabe se é uma notificação oficial, vinda da Cielo, ou se é uma notificação falsa, vinda de alguém mal intencionado?

**Comment by felipe7229** [comment]
Sim, é nesse sentido que pensei, eu vejo que teve mudança, recupero o paymentId e consulto.

**Comment by netojoaobatista** [comment]
Isso; muito mais seguro.

:smile:

**Comment by Akira-ux** [comment]
Boa tarde @netojoaobatista e @felipe7229, tudo joia com vocês?
Desculpe o incomodo, sei que já faz um muito tempo esse tópico referente ao Post Notification, porem poderiam me ajudar tirando uma duvida a respeito de que é preciso ter de parâmetro dentro do PHP para receber as informações na URL enviada do Post da cielo ?
Encaminhei emails para eles, porem falaram o de sempre para seguir a documentação e não tiram quaisquer duvida a respeito, e na documentação está um pouco confuso para min...

{ É possivel cadastrar uma informação para retorno do header da requisição. Basta entrar em contato com o Suporte Cielo e informar os itens abaixo
KEY - Nome do paramêtro
VALUE - Valor estático a ser retornado
Você pode cadastrar até 3 tipos de informação de retorno no header}

Se possível poderia me mostrar algum exemplo em produção de código para melhor entendimento de como funciona esse Post ?

**Comment by felipe7229** [comment]
Abaixo é o arquivo/url que irá receber o POST Notification no PHP. Existem outras formas de fazer, mas essa eu achei mais fácil.

`if ('POST' === $_SERVER['REQUEST_METHOD']) {

    $rawData = file_get_contents("php://input");
    $arr = json_decode($rawData, true);
    //Você faz as checagens que quiser, chama o banco de dados, etc.

}`
