### ISSUE TITLE
Venda com Cartão de Débito

### ISSUE THREAD

**Issue by brunohenri-g** [DeveloperCielo/API-3.0-PHP#77]
Boa noite, estou tentando efetuar uma venda com cartão de débito e o seguinte erro é retornado

```
            [returnCode:Cielo\API30\Ecommerce\Payment:private] => 05
            [returnMessage:Cielo\API30\Ecommerce\Payment:private] => Autorizacao negada
            [status:Cielo\API30\Ecommerce\Payment:private] => 3
```

Alguém saberia me dizer o que pode ser? Um detalhe é que o cartão de teste é correto

**Comment by felipe7229** [comment]
05 | Transação não autorizada. Cartão inadimplente (Do not honor). | Transação não autorizada. Não foi possível processar a transação. Questão relacionada a segurança, inadimplencia ou limite do portador. |

**Comment by netojoaobatista** [comment]
Qual cartão de teste está utilizando?

**Comment by brunohenri-g** [comment]
@netojoaobatista estou utilizando Cartão Visa - Bradesco

@felipe7229 Sim, eu li o manual, só que na descrição do status do código diz que pode ser um problema relacionado a segurança

**Comment by felipe7229** [comment]
em qual ambiente ? teste ou produção?

**Comment by brunohenri-g** [comment]
@felipe7229 Produção

**Comment by netojoaobatista** [comment]
Qual cartão de teste está utilizando? Se está no Sandbox e está usando um cartão de teste, você precisa seguir as regras de testes; por isso você precisa dizer qual cartão é. Agora, se está em produção, aí o problema é com o cartão mesmo que não está autorizando por 05.

**Comment by felipe7229** [comment]
aí está o problema então. Cartão de teste é so para ambiente de Testes, já em produção tem que ser utilizado um cartão real.

**Comment by brunohenri-g** [comment]
@felipe7229 No ambiente de testes eu utilizava cartão de teste. No ambiente real eu testei com cartão real.

**Comment by netojoaobatista** [comment]
@brunohenri-g, se está utilizando um cartão real e está recebendo 05, então o problema é real. Entre em contato com o comercial da Cielo; o código 05 significa inadimplência:

> 05 | Transação não autorizada. Cartão inadimplente (Do not honor). | Transação não autorizada. Não foi possível processar a transação. Questão relacionada a segurança, inadimplencia ou limite do portador. |

**Comment by netojoaobatista** [comment]
Se fosse 02 poderia ser com o volume de testes que fez com que caísse no anti-fraude, mas 05 é limite ultrapassado ou inadimplência.

**Comment by netojoaobatista** [comment]
A lista com todos os códigos de retorno de vendas estão aqui: [Códigos de Retorno de Vendas](https://developercielo.github.io/Webservice-3.0/#códigos-de-retorno-das-vendas)
