### ISSUE TITLE
Como mudar o nome que sai na fatura do Cartão ? 

### ISSUE THREAD

**Issue by felipe7229** [DeveloperCielo/API-3.0-PHP#78]
com o método setSoftDescriptor() não funcionou do jeito correto. E continua imprimindo o nome que o cliente cadastrou na CIELO, tem alguma maneira de mudar isso ? 

Desculpe a pergunta, pode ser que deva ser feito para a CIELO, mas caso alguém saiba me responder, aguardo a resposta. Obrigado.

**Comment by netojoaobatista** [comment]
Está seguindo as [regras de definição do softDescriptor](https://developercielo.github.io/Webservice-3.0/#soft-descriptor)?

> Permite que o lojista envie um texto complementar que será impresso na fatura do comprador junto com a identificação do nome da loja que consta no cadastro Cielo.
> * Tamanho máximo do campo: 13 caracteres.
> * Disponível apenas para as bandeiras Visa e MasterCard.
> * Não pode conter caracteres especiais.
> 
> Para conhecer e/ou alterar o nome da loja que esta cadastrado entre em contato com a central de relacionamento Cielo.

**Comment by felipe7229** [comment]
muito boa explicação.
