### ISSUE TITLE
Consultar todas as vendas.

### ISSUE THREAD

**Issue by paulolezak** [DeveloperCielo/API-3.0-PHP#79]
Como faço para fazer uma consulta retornando todas as vendas num intervalo de datas ?
Notei que só consigo consultar pelo Numero de identificação do Pagamento.

**Comment by felipe7229** [comment]
Acredito que essa consulta, só possa ser feito no PAINEL da CIELO, acredito que pela API não tenha suporte

**Comment by jhonnymakis** [comment]
Pela API retorna NULL, usando a URL /1/sales?merchantOrderId={merchantOrderId}

object(Cielo\Ecommerce\Sale)#137 (3) {
  ["merchantOrderId":"Cielo\Ecommerce\Sale":private]=>
  NULL
  ["customer":"Cielo\Ecommerce\Sale":private]=>
  NULL
  ["payment":"Cielo\Ecommerce\Sale":private]=>
  NULL
} 

No site da CIELO não vem todas as informações necessárias.

**Comment by netojoaobatista** [comment]
[Consulta de vendas](https://developercielo.github.io/manual/cielo-ecommerce#consultando-vendas) podem ocorrer pelo ID da venda ou pelo ID do vendedor.

**Comment by paulolezak** [comment]
PaymentId | Numero de identificação do Pagamento. | Texto | 36 | OBRIGATORIO = Sim

Se é obrigatorio informar o ( PaymentId ) numero de identificação de um pagamento, não seria consulta de todas as vendas. Seria de uma venda especifica,  não possuo  esse numero PaymentId ..

**Comment by netojoaobatista** [comment]
> não possuo esse numero PaymentId ..

O `PaymentId` é [retornado na criação de toda venda](https://developercielo.github.io/manual/cielo-ecommerce#resposta). Se criou uma venda, então é só armazenar o `paymentId` retornado.

[De qualquer forma, você também pode consultar a venda pelo ID do vendedor](https://developercielo.github.io/manual/cielo-ecommerce#consultando-uma-venda-pelo-identificador-da-loja).

**Comment by paulolezak** [comment]
A venda é feita em outro sistema, não tenho acesso,  agradeço a resposta, mais acho que só vou conseguir essas informações utilizando uma VAN autorizada, como a tivit accesstage ou etc... vou precisar dos dados da cielo, da rede etc..  eles devem fornecer de todas..

**Comment by netojoaobatista** [comment]
Entendi. Talvez - [e aí você vai precisar entrar em contato com a Cielo](https://desenvolvedores.cielo.com.br/api-portal/pt-br/contact) - o [EDI](https://developercielo.github.io/tutorial/edi#p%C3%BAblico-alvo) possa te ajudar.
