### ISSUE TITLE
Dividir pagamento

### ISSUE THREAD

**Issue by RodrigoGalter** [DeveloperCielo/API-3.0-PHP#8]
Existe a possibilidade de dividir o valor do pedido em 2 formas de pagamentos?

- Metade cartão de crédito.
- Metade boleto.

**Comment by netojoaobatista** [comment]
Isso você precisará fazer manualmente, só que enquanto o cartão você tem a resposta da autorização mais rapidamente, enquanto o boleto você precisará aguardar o cliente fazer o pagamento para poder liberar o pedido.

**Comment by RodrigoGalter** [comment]
Mesmo usando a opção de boleto da Cielo, poderia enviar duas formas de pagamento para um mesmo ID de pedido?

**Comment by netojoaobatista** [comment]
Nesse caso você precisará fazer uma divisão também na identificação do pedido; por exemplo, supondo que seu pedido seja o **12234**:

* Crédito - **12234-C**
* Boleto - **12234-B**

etc.

**Comment by jozephbrasil** [comment]
@netojoaobatista, aproveitando o barco.... como funciona essa API de Boleto da Cielo? Qual custo para utilização? O boleto é registrado?

**Comment by netojoaobatista** [comment]
@jozephbrasil, eu não sei responder quanto a custo; meu conhecimento limita-se à questões mais técnicas. Sobre o registro, agora é obrigatório que todo boleto seja registrado; só que isso não é na Cielo, mas todo e qualquer boleto; se não me engano é uma nova resolução do Banco Central.

**Comment by jozephbrasil** [comment]
@netojoaobatista, mas essa parte de boleto cielo, funciona tipo um gateway? A Cielo recebe e repassa ou é apenas um gerador de boleto com os dados de cobrança do lojista?

**Comment by netojoaobatista** [comment]
@jozephbrasil, eu acredito que funcione como um gateway, mas eu preciso verificar para te dar uma resposta mais correta.

**Comment by jozephbrasil** [comment]
@netojoaobatista, desculpe usar esse espaço para dúvidas... mas ligar para Cielo para conversar sobre essas coisas não tem sido um bom canal...

**Comment by netojoaobatista** [comment]
@jozephbrasil, esse espaço é justamente para tirar dúvidas, apesar de sua dúvida ficar melhor no repositório da documentação, já que pode ajudar outros usuários. De qualquer forma, se eu conseguir ajudar a resolver a dúvida, eu certamente ajudarei.

:smile:

**Comment by netojoaobatista** [comment]
@jozephbrasil:

1. Registro do boleto - está em desenvolvimento para o Bradesco, mas sem previsão ainda para Banco do Brasil.
2. Funcionamento do boleto - a Cielo apenas emite o boleto; eles não têm qualquer controle sobre pagamento e/ou depósito em conta.
3. Preços - realmente você precisará entrar em contato com o comercial.

:smile:
