### ISSUE TITLE
Alterando data do pagamento recorrente

### ISSUE THREAD

**Issue by marcelo2605** [DeveloperCielo/API-3.0-PHP#80]
Criei uma classe para fazer alterações em pagamentos recorrentes:

**UpdateRecurrentPaymentRequest.php**

```
<?php
namespace Cielo\API30\Ecommerce\Request;

use Cielo\API30\Ecommerce\Request\AbstractSaleRequest;
use Cielo\API30\Environment;
use Cielo\API30\Merchant;
use Cielo\API30\Ecommerce\RecurrentPayment;

class UpdateRecurrentPaymentRequest extends AbstractSaleRequest
{

    private $environment;

    private $type;

    private $recurrencyday;

    public function __construct($type, Merchant $merchant, Environment $environment)
    {
        parent::__construct($merchant);

        $this->environment = $environment;
        $this->type = $type;
    }

    public function execute($recurrentPaymentId)
    {
        $url = $this->environment->getApiURL() . '1/RecurrentPayment/' . $recurrentPaymentId . '/' . $this->type;
        $params = [];
        
        if ($this->recurrencyday != null) {
            $params['RecurrencyDay'] = $this->recurrencyday;
        }

        $url .= '?' . http_build_query($params);

        return $this->sendRequest('PUT', $url);
    }

    protected function unserialize($json)
    {
        return RecurrentPayment::fromJson($json);
    }

    public function getRecurrencyday()
    {
        return $this->recurrencyday;
    }

    public function setRecurrencyday($recurrencyday)
    {
        $this->recurrencyday = $recurrencyday;
        return $this;
    }
}
```

**CieloEcommerce.php**

```
...
use Cielo\API30\Ecommerce\Request\UpdateRecurrentPaymentRequest;

class CieloEcommerce
{
  ...
  public function changeDayRecurrentPayment($recurrentPaymentId, $recurrencyday = null)
    {
        $changeDayRecurrentPaymentRequest = new UpdateRecurrentPaymentRequest('RecurrencyDay', $this->merchant, $this->environment);

        $changeDayRecurrentPaymentRequest->setRecurrencyday($recurrencyday);

        return $changeDayRecurrentPaymentRequest->execute($recurrentPaymentId);
    }
  ...
```

Chamando o método:

`$changeday = (new CieloEcommerce($merchant, $environment))->changeDayRecurrentPayment($id, $day);`

Mas ele retorna o seguinte erro:

> Fatal error: Uncaught Cielo\API30\Ecommerce\Request\CieloRequestException: Request Error in /var/www/public/wp-content/themes/site/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php:85 Stack trace: #0 /var/www/public/wp-content/themes/site/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php(67): Cielo\API30\Ecommerce\Request\AbstractSaleRequest->readResponse(400, '[\r\n {\r\n "Co...') #1 /var/www/public/wp-content/themes/site/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/UpdateRecurrentPaymentRequest.php(37): Cielo\API30\Ecommerce\Request\AbstractSaleRequest->sendRequest('PUT', 'https://apisand...') #2 /var/www/public/wp-content/themes/site/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(118): Cielo\API30\Ecommerce\Request\UpdateRecurrentPaymentRequest->execute('8b4050d5-1a79-4...') #3 /var/www/public/wp-content/themes/site/inc/cielo.php(100 in /var/www/public/wp-content/themes/site/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php on line 85

**Comment by felipe7229** [comment]
opinião minha. Joga esse 
$changeday =   (new CieloEcommerce($merchant, $environment))->changeDayRecurrentPayment($id, $day) 

Dentro de um try catch, porque o Erro que está dando é referente a  exceção não capturada. EU ACHO!

**Comment by felipe7229** [comment]
Ou então, coloca no começo do arquivo PHP  error_reporting(E_ALL);
ini_set("display_errors", 1);
 e veja o error_log

**Comment by marcelo2605** [comment]
Valeu @felipe7229, mas acho que descobri o problema.

A data não pode ir no header da requisição. Precisa ir no body.

A função que faz isso é a `sendRequest()`, que está em AbstractSaleRequest.php.

Para não mexer nela, já que outras partes do código a usam, criei uma nova função idêntica, mas passando uma variável $value:

`protected function sendRequest2($method, $url, $value = null)`

E no UpdateRecurrentPaymentRequest.php, eu verifico a variável do dia:

```
if ($this->recurrencyDay != null) {
    $value = $this->recurrencyDay;
}
```

E passo ela na função:

`return $this->sendRequest2('PUT', $url, $value);`

Funcionou, mas com certeza dá para melhorar isso.

**Comment by muvasco** [comment]
@marcelo2605 dê uma olhada no PR que abri: #82 

Eu precisei implementar o cancelamento das recorrências em um projeto meu e aproveitei e juntei o que vc estava querendo também.

A classe AbstractSaleRequest até tinha como passar um parâmetro no body da requisição, mas ela restringe apenas à classe Sale. Pensei em torná-la mais genérica, para poder continuar usando-a nas requisições de recorrência, seguindo o mesmo padrão.

**Comment by felipe7229** [comment]
Top

**Comment by marcelo2605** [comment]
@muvasco  Bem melhor!

Só uma dúvida: no AbstractRequest.php, você alterou a linha que gera o método sendRequest para

`protected function sendRequest($method, $url, $content = null)`

Mas a variável $sale não está mais listada nos parâmetros. Ainda é possível usá-la?

**Comment by muvasco** [comment]
@marcelo2605 é possível sim, eu renomeei a variável dentro da função também, nos locais onde ela era utilizada.

**Comment by marcelo2605** [comment]
Tem razão. Vou testar aqui. Obrigado pela contribuição!
