### ISSUE TITLE
Alguém tem ideia do por quê que não consigo cancelar compras feitas no meu site?

### ISSUE THREAD

**Issue by felipe7229** [DeveloperCielo/API-3.0-PHP#81]
Tanto no painel quanto pela API retorna a mesma coisa. 

{
    "Status": 2,
    "ReasonCode": 7,
    "ReasonMessage": "Denied",
    "ProviderReturnCode": "6",
    "ProviderReturnMessage": "Nao foi possivel cancelar a Transacao",
    "ReturnCode": "6",
    "ReturnMessage": "Nao foi possivel cancelar a Transacao",
    "Links": [
        {
            "Method": "GET",
            "Rel": "self",
            "Href": "https://apiquery.cieloecommerce.cielo.com.br/1/sales/24c4c996-6fb3-4e3a-a746-fb04774f3795"
        },
        {
            "Method": "PUT",
            "Rel": "void",
            "Href": "https://api.cieloecommerce.cielo.com.br/1/sales/24c4c996-6fb3-4e3a-a746-fb04774f3795/void"
        }
    ]
}

Só para esclarecer, só trabalho com vendas recorrentes (assinaturas). Alguém consegue me explicar?

**Comment by muvasco** [comment]
@felipe7229 como está o conteúdo das suas requisições, consegue colar aqui?

**Comment by felipe7229** [comment]
então, não precisa de conteúdo né, eu só preciso informar o payment_id e o amount para cancelar totalmente

**Comment by muvasco** [comment]
Sim, eu quis dizer os parâmetros e acabei falando conteúdo.

Acredito que você esteja tentando cancelar pelo método de cancelamento de venda simples: https://developercielo.github.io/manual/api-cielo-ecommerce?shell#cancelando-uma-venda, por isso não está conseguindo.

Como você está trabalhando com vendas recorrentes, deve cancelar desta forma: https://developercielo.github.io/manual/api-cielo-ecommerce?shell#desabilitando-um-pedido-recorrente

Atente-se que o parâmetro necessário é o RecurrentPaymentId e não o PaymentId nesse caso.

**Comment by felipe7229** [comment]
Sim, eu envio para endpoint /Deactive, eu consigo. Mas para eu cancelar a transação ? Quero estornar o dinheiro para meu cliente

**Comment by felipe7229** [comment]
Eu conseguia realizar esse estorno e até cancelar a venda. Agora não estou conseguindo mais

**Comment by muvasco** [comment]
Entendi agora.

Fazendo a requisição pelo Postman também acontece a mesma coisa? Se por lá funcionar, é algum problema no código provavelmente.

Se não, pode ser problema com algum dado enviado. Acho que seria legal entrar em contato com o suporte da Cielo também para ver se eles conseguem olhar os dados enviados e verificar se tem algo errado.

**Comment by felipe7229** [comment]
Sim, tentei pelo postman, e nada. Tentei pelo próprio painel deles, sempre dando o mesmo ERRO, e pelo painel sempre devolvem códigos de erros mistériosos tipo 6, 865.

**Comment by muvasco** [comment]
Tenta ver com o suporte deles então. Já entrei em contato e conseguiram resolver:
cieloecommerce@cielo.com.br
Tel: 4002-9700 (Capitais e regiões metropolitanas)
0800-570-1700 (Demais localidades) opção 1

**Comment by felipe7229** [comment]
Mandei um e-mail, as vezes eles levam 2 dias para responder. Quando responderem eu te retorno para você ficar sabendo o ocorrido. Muito obrigado pela atenção. Abraços

**Comment by muvasco** [comment]
Show, valeu @felipe7229!

**Comment by GiovaneLucas** [comment]
Alguma solução para o problema?
Estou passando pela mesma situação na aplicação em que estamos trabalhando.

**Comment by felipe7229** [comment]
@GiovaneLucas é o seguinte cara. Você esta tentando cancelar a compra (estorno) ou cancelando a recorrencia? Porque se for cancelar a recorrencia na API existe um método pronto já para isso e bastante simples, entretanto se for estornar a compra, eu consegui pouquissimas vezes, as vezes dava certo, outras vezes não, não sei dizer qual o problema em cancelar, mas sempre fiquei nessa dúvida.

**Comment by suppera** [comment]
Olá, verifique no suporte da Cielo, se a transação tem mais de 24h talvez precisa habilitar o seu cadastro para poder estornar. Se estiver usando a SandBox, precisa habilitar também para poder cancelar.

**Comment by GiovaneLucas** [comment]
Valeu pela resposta @felipe7229 .
Seguinte.. estou apontando para o servidor de produção mesmo, realizando um estorno de uma compra, não cancelando recorrência. O estranho é que com o mesmo cartão cancelei alguns pagamentos realizados mas outros simplesmente vem o retorno 6-Denied. É como vc disse, as vezes da certo outras vezes não.

**Comment by felipe7229** [comment]
isso mesmo @GiovaneLucas. As vezes dava certo e com o mesmo cartão as vezes não dava. Sinceramente não consegui entender até hoje. Ainda bem que não precisei implementar esse tipo de operação de cancelamento no software

**Comment by GiovaneLucas** [comment]
Aí é complicado...
Alguém mais passou por algo parecido?

**Comment by felipe7229** [comment]
Eu fiquei impaciente e não tentei saber o motivo. Eu lembro que no email que mandei para a Cielo, eles me pediram para entrar em contato com o Financeiro, se não me engano.

**Comment by GiovaneLucas** [comment]
Obrigado @felipe7229  vou ver o que faço aqui, e tentar falar com eles

**Comment by mateusrama** [comment]
Estou com o mesmo problema, alguem tem uma solução?
