### ISSUE TITLE
Problema - ReturnCode = 001

### ISSUE THREAD

**Issue by 7evenbr** [DeveloperCielo/API-3.0-PHP#83]
Estou tendo um problema c/ uma nova implementação. Ao utilizar exatamente o mesmo código de um ecommerce que ja esta funcionando (Exceto o Merchant ID e o Merchant Key) a transação não é computada na cielo em ambiente de produção, no ambiente de teste funciona perfeito.

É retornado:
ReturnCode: 001
ReturnMessage: <![CDATA[O XML informado nÃ£o Ã© valido:- cvc-minInclusive-valid: Value '0' is not facet-valid with respect to minInclusive '1' for type '#AnonType_valorDadosPedido'.']]>

Aguardo ajuda. obrigado

**Comment by felipe7229** [comment]
Estranho, pode mandar o json retornado inteiro? e parte do código? Obrigado
