### ISSUE TITLE
Problema Sandbox e Produção

### ISSUE THREAD

**Issue by moobeinc** [DeveloperCielo/API-3.0-PHP#84]
Pessoal! Estou utilizando a SDK porém qdo uso em Sandbox as transações fluem normalmente, porém qdo troco as credenciais e mudo para produção não funciona, não me retorna nada nem erro.

A cielo ja homologou porém não esta funcionando mais.

O que poderia ser? ja olhei e revirei o código.

**Comment by felipe7229** [comment]
você lembrou de setar o ambiente como produção?
$environment = $environment =  Environment::production();
ou
$environment = null

**Comment by felipe7229** [comment]
mostre o código para gente
