### ISSUE TITLE
American Express não funciona.

### ISSUE THREAD

**Issue by mvnp** [DeveloperCielo/API-3.0-PHP#85]
O único cartão que não funciona no formulário de pagamento por cartão de crédito que eu fiz é o American Express. Existe alguma implementação adicional que precisa ser feita para que o carão funcione. Obrigado por alguma ajuda.

**Comment by netojoaobatista** [comment]
O que não funciona? Dá algum erro da API? Erro no SDK? Qual o erro?

**Comment by mvnp** [comment]
Simplesmente dá não autorizado. Estranhamente todos os outros cartões funcionam e Amex não.

**Comment by netojoaobatista** [comment]
@mvnp, já normalizou, ou ainda está com problemas? Se estiver, qual exatamente é o código da não autorização?
