### ISSUE TITLE
Como fazer a transação mas antes saber se o cartão foi aprovado ou não ?

### ISSUE THREAD

**Issue by otaviobarreto** [DeveloperCielo/API-3.0-PHP#86]
Olá estou usando a API WEB SERVICE 3.0 PHP [https://github.com/DeveloperCielo/API-3.0-PHP/]( https://github.com/DeveloperCielo/API-3.0-PHP/)  instalei via composer, configurei o código para minha MERCHANT KEY E MERCHANT ID e tudo funcionou, porém não encontrei alguma descrição para antes de efetuar o pagamento saber se o cartão foi aprovado ou não. segue o exemplo abaixo: 

```
`<?php
require 'vendor/autoload.php';

use Cielo\API30\Merchant;

use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;

use Cielo\API30\Ecommerce\Request\CieloRequestException;
// ...
// Configure o ambiente
$environment = $environment = Environment::sandbox();

// Configure seu merchant
$merchant = new Merchant('MERCHANT ID', 'MERCHANT KEY');

// Crie uma instância de Sale informando o ID do pagamento
$sale = new Sale('123');

// Crie uma instância de Customer informando o nome do cliente
$customer = $sale->customer('Fulano de Tal');

// Crie uma instância de Payment informando o valor do pagamento
$payment = $sale->payment(15700);

// Crie uma instância de Credit Card utilizando os dados de teste
// esses dados estão disponíveis no manual de integração
$payment->setType(Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "Visa")
        ->setExpirationDate("12/2018")
        ->setCardNumber("0000000000000001")
        ->setHolder("Fulano de Tal");

// Crie o pagamento na Cielo
try {
    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

    // Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
    // dados retornados pela Cielo
    $paymentId = $sale->getPayment()->getPaymentId();

    // Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
    $sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);

    // E também podemos fazer seu cancelamento, se for o caso
    $sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);
} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}
// ...`
```

antes de executar o código da transação, como saber se o cartão foi aprovado ou não? e caso for aprovado prosseguir para a transação, caso não for aprovado prosseguir para o cancelamento?

**Comment by felipe7229** [comment]
Pela experiência da implementação que eu fiz, existem dois jeitos: O primeiro é verificando o cartão se ele é correto ou não (essa possibilidade não diz se o cartão tem limite, está cancelado ou não, apenas diz se o cartão é valido). O outro jeito é fazendo um request com o método createSale(), no retorno dele ($sale) irá aparecer o status da transação, se ela foi aprovada ou não, caso não, devolverá o erro e a mensagem. Tudo isso está documentado no Manual da Cielo.

**Comment by otaviobarreto** [comment]
Olá felipe, me explica melhor? você, poderia deixar um exemplo básico de código como eu faria esse request no método createSale() ? não encontrei nada sobre isso na documentação.

**Comment by felipe7229** [comment]
try {
    // Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
    $sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);
    //Se você der um print_r($sale) vai aparecer o json de retorno da CIELO, ai voce poderá ver se deu sucesso ou não.
  
} catch (CieloRequestException $e) {
    // Em caso de erros de integração, podemos tratar o erro aqui.
    // os códigos de erro estão todos disponíveis no manual de integração.
    $error = $e->getCieloError();
}

**Comment by otaviobarreto** [comment]
Obrigado felipe, consegui o retorno do JSON, agora ó configurar as mensagens de erro.

**Comment by felipe7229** [comment]
De nada, qualquer coisa é só gritar, se eu consegui ajudar fico feliz também.
