### ISSUE TITLE
Criando uma venda com Cartão Tokenizado

### ISSUE THREAD

**Issue by rodolfowagner** [DeveloperCielo/API-3.0-PHP#88]
A API 3.0 é excelente, mas não encontrei como utilizar recursos como criar uma venda com Cartão Tokenizado e transferência on line.

Qual a forma correta de fazer a criação da venda na API com o token do cartão?

Obrigado!

**Comment by netojoaobatista** [comment]
A seção [Criando uma venda com Cartão Tokenizado](https://developercielo.github.io/Webservice-3.0/#criando-uma-venda-com-cartão-tokenizado) trata exatamente sobre isso, @rodolfowagner.

**Comment by rodolfowagner** [comment]
Então, obrigado pela resposta. 
Mas me refiro aos exemplos que constam em : https://github.com/DeveloperCielo/API-3.0-PHP
São super fáceis e simples de entender, mas não consegui fazer utilizando os recursos da SDK API-3.0 PHP.

**Comment by rodolfowagner** [comment]
Na SDK não encontrei nenhuma função que crie uma venda com cartão tokenizado no mesmo padrão de uma venda com cartão de crédito, a qual segue esse formato;

$payment
->setType(Payment::PAYMENTTYPE_CREDITCARD)
->creditCard($dataCartao['codigo'], $dataCartao['bandeira'])

A minha dúvida é se existe algo nesse padrão já disponibilizado pela SDK.
Eu criei uma função para criar a venda, mas se possível eu gostaria de usar os recursos da SDK para manter o padrão do projeto..
