### ISSUE TITLE
Manual vs Api - divergência no ReturnCode

### ISSUE THREAD

**Issue by gildonei** [DeveloperCielo/API-3.0-PHP#89]
Fazendo testes e estudando sobre a API v3.0 observei que a **ReturnCode** e **ReturnMessage** divergem dos códigos de retorno da venda constantes no manual - https://developercielo.github.io/Webservice-3.0/?shell#códigos-de-retorno-das-vendas.

Utilizando o cartão de **final 1** obtém-se retorno da API ** status => 1** e **ReturnCode => 4** com **ReturnMessage => Operation Succeful**, porém no manul o ReturnCode => 4 seria referente à **Transação não autorizada. Cartão bloqueado pelo banco emissor.**

Gostaria de entender melhor o pq da divergência e saber onde capturo exatamente o código de retorno da venda, pois para vendas em CC e CD refere-se aos ReturnCode

![image](https://user-images.githubusercontent.com/1370979/31995099-dec64192-b961-11e7-9ec5-4e09699fa062.png)

**Comment by felipe7229** [comment]
Nossa bem estranho isso em, pensei que estava em produção, mas logo vi as URL's. Nunca vi esse "erro" acontecer.

**Comment by netojoaobatista** [comment]
@gildonei, a resposta está exatamente como descrito no manual, veja:

![image](https://user-images.githubusercontent.com/273586/32278111-c005b1c6-befb-11e7-990b-d9098be2c7ba.png)

Se, no sandbox, você enviar um cartão com final 1, o código de retorno será *4/6* e a mensagem será *Operation Successful*, exatamente como você está recebendo.

**Comment by gildonei** [comment]
Então no Sandbox, nunca conseguirei testar e verificar os demais códigos de retorno da venda, ele sempre trará os códigos acima da tabela, mesmo que queira validar uma "insuficiência de fundos" por exemplo, sempre terei os retornos acima e nunca conseguirei testar um **returnCode 51** por exemplo **Transação não autorizada. Limite excedido/sem saldo.**

**Comment by felipe7229** [comment]
Desculpa me intrometer, mas sim @gildonei. Os retornos serão sempre como a tabela acima em ambiente de testes.

**Comment by gildonei** [comment]
Blz, obrigado pela ajuda aí.
