### ISSUE TITLE
Problema com composer e configuração inicial

### ISSUE THREAD

**Issue by teuzinPereira** [DeveloperCielo/API-3.0-PHP#9]
Ola equipe, fiz a instalação com o composer normalmente e fiz o require_once do autoload na pasta vendor. Porem já aparece o erro abaixo no momento que instancio a classe 'Environment'.

 Fatal error: Uncaught Error: Class 'Environment' not found in C:\xampp\htdocs\cieloNew\pagamento.php:11 Stack trace: #0 {main} thrown in C:\xampp\htdocs\cieloNew\pagamento.php on line 11

Teriam um cod exemplo da configuração básica antes de usar o cod descrito neste repositório? Senão, pelo menos um tutorial que apresente melhor esta configuração antes de começar o cod.

**Comment by netojoaobatista** [comment]
Velhinho, você precisa especificar o namespace dos participantes que irá usar:

```php
require 'vendor/autoload.php';

use Cielo\API30\Merchant;
use Cielo\API30\Ecommerce\Environment;

//...
```

**Comment by teuzinPereira** [comment]
Ola neto, eu tinha coloca um link errado no use. 

Obrigado pela atenção.
