### ISSUE TITLE
Duvidas checkout API

### ISSUE THREAD

**Issue by felipefreitasweb** [DeveloperCielo/API-3.0-PHP#90]
Olá, 

Estou implementado a API 3.0  e fiquei com algumas dúvidas, se puderem me ajudar...

- Somente com o Status eu ja consigo garantir se a venda foi ou não concretizada? Por exemplo se retornou 1 isso ja garante que tudo deu certo? Ou preciso checar outros dados também? (Ref.: https://developercielo.github.io/Webservice-3.0/#status)

- E quando uma transação  retorna 0 (Aguardando atualização de status) significa que preciso ter algum serviço consultando  essa transação ? 

Meu projeto é fechado pra o uso de uma pessoa apenas, não é uma loja.

Obrigado desde ja.

**Comment by netojoaobatista** [comment]
@felipefreitasweb, veja a seção [Sobre os Códigos](https://developercielo.github.io/manual/cielo-ecommerce#sobre-os-c%C3%B3digos) do manual.
