### ISSUE TITLE
Qual a nomenclatura correta ao passar a bandeira do cartão?

### ISSUE THREAD

**Issue by otaviobarreto** [DeveloperCielo/API-3.0-PHP#92]
Fiz um teste com um mastercard
```
$payment->setType(Payment::PAYMENTTYPE_CREDITCARD)
        ->creditCard("123", "bandeira") //nomenclatura aqui
        ->setExpirationDate("05/2018")
        ->setCardNumber("****************")
        ->setHolder("Nome do consumidor"); 

```
Até ai tudo bem, testei "mastescard" minusculo e separado, mas deu um erro, gostaria de saber se existe uma forma correta para nomenclatura da bandeira, pois isso não encontrei na documentação da API,  em relação a bandeira do cartão, existe algum problema com Case-sensitive ou algo do tipo? qual seria o jeito correto?

**Comment by netojoaobatista** [comment]
Essa informação está no manual, veja: [Criando uma transação simples](https://developercielo.github.io/manual/cielo-ecommerce#requisi%C3%A7%C3%A3o)

> Bandeira do cartão (Visa / Master / Amex / Elo / Aura / JCB / Diners / Discover).

**Comment by otaviobarreto** [comment]
Obrigado!
