### ISSUE TITLE
Checkout diretamente na Cielo

### ISSUE THREAD

**Issue by paulohendges** [DeveloperCielo/API-3.0-PHP#98]
Olá,

Gostaria de saber qual a forma de efetuar o checkout diretamente pelo painel da Cielo.
Ex: Hoje temos uma aplicação que utiliza o pagseguro e teremos que migrar para a Cielo. Porém, gostaria de saber se tem algum exemplo nesta aPI que faça apenas o redirect para o painel da Cielo onde o próprio usuário irá informar seus dados de pagamento e a forma... ?

Vi que nesta lib somente contém exemplos de utilização para cartão de crédito, tokenização e outros, menos o de checkout direto, onde eu enviaria somente os dados do carrinho, cliente e produto.

**Comment by netojoaobatista** [comment]
Esse SDK faz a integração com a API da Cielo. Se estiver procurando, porém, pelo produto Checkout Cielo, veja o [manual de integração](https://developercielo.github.io/manual/checkout-cielo).
