### ISSUE TITLE
TokenizeCard

### ISSUE THREAD

**Issue by Minotti** [DeveloperCielo/API-3.0-PHP#99]
Bom dia, porque a função tokenizeCard foi removida? Agora pra gerar o token de um cartão é só criando uma venda?

De todo modo removam do README a parte de tokenizar um cartão, pois a mesma não é possível utilizar.

Detalhe: a versão 1.0 não instala, somente instala a 1.1 onde não existe a parte de tokenização.

Obrigado

**Comment by netojoaobatista** [comment]
> Bom dia, porque a função tokenizeCard foi removida?

Não foi: [CieloEcommerce::tokenizeCard](https://github.com/DeveloperCielo/API-3.0-PHP/blob/master/src/Cielo/API30/Ecommerce/CieloEcommerce.php#L167)

**Comment by Minotti** [comment]
Na versão 1.1 essa função aí não existe. E quando tento instalar a versão 1.0 não é encontrado.

**Comment by netojoaobatista** [comment]
```
composer require "developercielo/api-3.0-php:dev-master"
```

Isso vai utilizar a versão do `master` do projeto.

```
composer require "developercielo/api-3.0-php"
```

Isso vai utilizar a maior versão disponível, mas que não necessariamente contém todos os recursos do `master` do projeto.

```
composer require "developercielo/api-3.0-php:dev-master:1.2.0"
```

Isso vai utilizar a versão `1.2.0` do projeto.

**Comment by netojoaobatista** [comment]
Btw, para instalar a versão **1.0.0**, só fazer:

```
composer require "developercielo/api-3.0-php:1.0.0"
```

**Comment by Minotti** [comment]
Instalar a versão master do projeto é uma boa ideia?

**Comment by netojoaobatista** [comment]
Para testes, sim; para produção, somente após os testes. Mas tente a 1.2.0 que certamente resolverá seu problema:

```
composer require "developercielo/api-3.0-php:dev-master:1.2.0"
```

**Comment by Minotti** [comment]
Muito bom, obrigado
